### ISSUE TITLE
Rename "admin123" URL (admin panel)

### ISSUE THREAD

**Issue by Compstuff** [pH7Software/pH7-Social-Dating-CMS#431] opened 2019-02-04 12:05 UTC
Hello,

I just installed the software and I am testing it... I am definitely impressed and will leave a review once I have had time to thoroughly test it. I am now wondering if the admin URL can be named something other than admin123... in general practice I never use the name admin for anything.

Thanks

**Comment by zeerprettiggestoord** [comment] 2019-02-04 12:07
Lookup the wiki. There it is explained step by step

Op ma 4 feb. 2019 13:05 schreef Compstuff <notifications@github.com:

**Comment by pH-7** [comment] 2019-02-05 06:42
Like what @zeerprettiggestoord said :),
Yes, it's explained in the doc, here: https://ph7cms.com/doc/en/rename-the-admin-folder

Finally, since [v12.1](https://ph7cms.com/ph7cms-12-1-released/), all URL lookups are cached for optimization purpose.

Because of that, you will also have to to remove `/_protected/data/cache/pH7_cache/str/uri/` folder. This folder will be regenerated and the URIs cached recreated.

All the best

**Comment by pH-7** [comment] 2019-02-06 18:01
Is it still an issue @Compstuff
Everything working fine now?

**Comment by pH-7** [comment] 2019-02-08 06:57
Please close this ticket if the problem is solved. Let me know if this isn't the case.
Thank you @Compstuff

**Closed** 2019-02-12 07:54 UTC
