### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by XxPoNaGeXx** [pH7Software/pH7-Social-Dating-CMS#146] opened 2017-11-11 20:51 UTC
When users are signing up it just takes them back to the signup page and does nothing...

**Comment by XxPoNaGeXx** [comment] 2017-11-11 20:55
I also cannot log into my admin account...

**Comment by XxPoNaGeXx** [comment] 2017-11-11 20:55
https://imgur.com/jWVoR2v

**Comment by XxPoNaGeXx** [comment] 2017-11-11 20:56
I checked the database to make sure the admin details are on it and correct, they are.

**Comment by pH-7** [comment] 2017-11-11 22:46
Hi @XxPoNaGeXx 

It looks like a problem with the session or your server has permission issues to write the sessions.
You can contact your host for asking them to investigate and check their log.

Concerning the Admin Login form, it is located at http://your-site.com/**admin123**/

Let me know if the problem persists or if you fix it

**Comment by XxPoNaGeXx** [comment] 2017-11-11 22:48
Hey @pH-7 I am using my own server. (Linux Debian 8)

Would you be able to give me the commands to fix the write perms?

**Comment by pH-7** [comment] 2017-11-12 02:59
Probably from your server then! I cannot know like that the exact fix and your config but I suggest you to look at stackoverflow 
Or try to install pH7CMS on MAMP (if Mac), XAMPP/WampServer (if Windows) or try on a web hosting (if you got one).

Please let me know ;)

**Comment by XxPoNaGeXx** [comment] 2017-11-12 09:37
It's already installed on a XAMMP server which is the Linux equivalent

**Comment by pH-7** [comment] 2017-11-14 19:02
The problem is definitely from there then. Please try to install pH7CMS on a different environment or investigate on the issue. Probably someone else occurred the same problem with XAMMP. Try to see on stackoverflow.com

Hope that helps!

Have . great day

**Comment by pH-7** [comment] 2017-11-15 03:56
Close it for now in order to keep the workflow clean. PLEASE **reopen** it if the problem still occur or if you found the trick/fix to fix your problem.

**Closed by pH-7** 2017-11-15 03:56 UTC
