### ISSUE TITLE
WAMP 64-bit installation completes ok. All .php requests return 500 internal server error.

### ISSUE THREAD

**Issue by jay0kay** [pH7Software/pH7-Social-Dating-CMS#348] opened 2018-11-05 22:17 UTC
1) Message: Parsing code unset! 

#0 ...\_protected\framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl.class.php(721): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\Syntax\Curly->parse()

class Curly extends Syntax implements Parsable
{
    public function parse()
    {
        if ($this->isCodeUnset()) {
            throw new EmptyCodeException(
                'Parsing code unset!',
                EmptyCodeException::CURLY_SYNTAX
            );
        }
        ...
}

2) httpd.conf edited as shown below and apache24 restarted.

LoadModule rewrite_module modules/mod_rewrite.so

<Directory>
    Options All
    AllowOverride All
</Directory>

3. phpinfo()

Apache Version | Apache/2.4.37 (Win64) PHP/7.3.0RC4
Loaded Modules | [list includes] mod_rewrite
HTTP_MOD_REWRITE | On
PHP Version | 7.3.0RC4

Any assistance would be greatly appreciated.

**Comment by pH-7** [comment] 2018-11-08 19:06
@jay0kay 
1. Are you sure you uploaded ALL files to your server? Please make sure.
2. Have you changed the theme to another one? Did you remove a template folder..?
3. Did you try to upgrade your pH7Builder website from previous version? Please try to reinstall a fresh installation (freshly downloaded from https://sourceforge.net/projects/ph7socialdating/)
4. If you did custom modifications. Please revert them, and add bit per bit to see from which modification the problem is from.

I really hope it helps! 🤞

I will close it by now (because most of the people won't never come back). Please reopen it if the problem persists despite my instructions.

**Comment by pH-7** [comment] 2018-11-08 19:07
P.S. And don't forget to star the repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Closed by pH-7** 2018-11-08 19:07 UTC
