### ISSUE TITLE
"Meet & date amazing people" on splash homepage not translated

### ISSUE THREAD

**Issue by edmundosantana** [pH7Software/pH7-Social-Dating-CMS#199] opened 2018-04-24 06:15 UTC
Hello, I reviewed the software translation in Portuguese. Even so, on the main page the message: Meet & date amazing people near is not translated.
Another thing; not everything is possible to translate from the Global.po file. In this case, how do you translate these parts ??

**Comment by pH-7** [comment] 2018-04-24 18:17
Hi @edmundosantana 
As far as I can see, https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/5dd3c89a76aa6f3371b82f819ccd6a2c33aab23d/_protected/app/system/modules/user/views/base/tpl/main/user_promo_block.inc.tpl#L9 should be translatable
and actually present in [global.pot](https://github.com/pH7Software/pH7-Internationalization/blob/master/global.pot). 
<img width="937" alt="screen shot 2018-04-24 at 19 16 27" src="https://user-images.githubusercontent.com/1325411/39205969-12358d78-47f4-11e8-94d7-bcda546c3ae4.png">

Now, maybe it wasn't translated in the [current Portuguese version](https://github.com/pH7Software/pH7-Internationalization)...

**Comment by pH-7** [comment] 2018-04-25 17:38
Hope that helped @edmundosantana? Let me know if the issue is solved by now (and can be closed)?

**Comment by pH-7** [comment] 2018-04-26 18:04
Okay, sorry. I see now that this string wasn't added for some reason into the Portuguese translation. Like I said to you by email, you should add the following:
```
#: _protected/data/cache/pH7tpl_compile/user_92496e072f4a216a2e22292546425ec0/base/main/user_promo_block.inc.cpl.php:19
msgid "Meet &amp; date amazing people near %0%!"
msgstr "" # Your Portuguese Translation these
```

**Comment by pH-7** [comment] 2018-04-26 18:06
I'm closing it since the issue is solved by now 🎉 
Thanks!

**Closed by pH-7** 2018-04-26 18:06 UTC
