### ISSUE TITLE
Database Install Problems Windows Wamp

### ISSUE THREAD

**Issue by AndrewCraft-Server** [pH7Software/pH7-Social-Dating-CMS#95] opened 2016-08-23 10:13 UTC
I have MySQL strict mode disabled but i get this error from official download and the repository  
Error connecting to your database.
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'server.ph7_settings' doesn't exist

but it was already in the database setting things up it just did not create this file any idea's?

**Comment by pH-7** [comment] 2016-08-23 18:35
Hi! Last time (a month ago) I ran pH7CMS on Wamp, it was working well.
I don't have Windows right now. So I can help you and solve your problem if you do the following for me:
Open your PHPMyAdmin (localhost/phpmyadmin), create a new database. GO to -> SQL and execute the following files  (by following the order given)

- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_SchemaGame.sql

-https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_SampleData.sql

- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

When you execute the third one, you should see an error showing on your phpmyadmin. Please copy/paste it here

**Comment by pH-7** [comment] 2016-08-23 18:38
Sorry, made a mistake. Here is the correct thing to do:

Hi @AndrewCraft-Server! Last time (a month ago) I ran pH7CMS on Wamp, it was working well.
I don't have Windows right now. So I can help you and solve your problem if you do the following for me:
Open your PHPMyAdmin (localhost/phpmyadmin), create a new database. GO to -> SQL and execute the following files  (by following the order given)

- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_SchemaGame.sql

- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_DataGame.sql

- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

When you execute the third one, you should see an error showing on your phpmyadmin. Please copy/paste it here

**Comment by pH-7** [comment] 2016-08-24 16:52
Hi AndrewCraft-Server! I can't reproduce the error on my Wamp. Like I said, please post ASAP your error your got after executing the SQL scripts manually so i can be fixed before Friday

**Comment by pH-7** [comment] 2016-08-24 16:52
@AndrewCraft-Server If you can tele your current Wamp version, it would be great

**Comment by pH-7** [comment] 2016-08-24 16:52
@AndrewCraft-Server If you can tele your current Wamp version, it would be great (but optional)

**Comment by pH-7** [comment] 2016-08-25 17:35
@AndrewCraft-Server, I know you are not a bad guy. Please be cool and replay to my question. This will also help lot of other users who might got the same issue than you.

**Comment by AndrewCraft-Server** [comment] 2016-08-28 00:15
Sorry i was in another state fixing a hard drive in my server i will do what you asked!

**Comment by AndrewCraft-Server** [comment] 2016-08-28 00:28
Static analysis:

3 errors were found during analysis.

A comma or a closing bracket was expected. (near "lang" at position 944)
Unexpected beginning of statement. (near "5" at position 957)
Unrecognized statement type. (near "NOT NULL" at position 960)
SQL query:

CREATE TABLE IF NOT EXISTS pH7_Members ( profileId int(10) unsigned NOT NULL AUTO_INCREMENT, email varchar(120) NOT NULL, username varchar(40) NOT NULL, password varchar(120) NOT NULL, firstName varchar(50) DEFAULT NULL, lastName varchar(50) DEFAULT NULL, birthDate date NOT NULL DEFAULT '0000-00-00', sex enum('male','female','couple') NOT NULL DEFAULT 'female', matchSex set('male','female','couple') NOT NULL DEFAULT 'male', ip varchar(45) NOT NULL DEFAULT '127.0.0.1', bankAccount varchar(150) DEFAULT NULL, groupId tinyint(2) unsigned NOT NULL DEFAULT 2, membershipDate datetime DEFAULT NULL, userStatus tinyint(1) unsigned NOT NULL DEFAULT 1, joinDate datetime DEFAULT NULL, lastActivity datetime DEFAULT NULL, lastEdit datetime DEFAULT NULL, avatar char(5) DEFAULT NULL, approvedAvatar tinyint(1) unsigned NOT NULL DEFAULT 1, featured tinyint(1) unsigned NOT NULL DEFAULT 0, lang varchar(5) NOT NULL DEFAULT 'en_US', hashValidation varchar(40) DEFAULT NULL, isTwoFactorAuth enum('1','0') DEFAULT '0', twoFactorAuthSecret varchar(40) DEFAULT NULL, views int(11) NOT NULL DEFAULT 0, reference varchar(255) DEFAULT NULL, votes int(11) DEFAULT 0, score float DEFAULT 0, credits int(6) unsigned NOT NULL DEFAULT 0, affiliatedId int(10) unsigned NOT NULL DEFAULT 0, active tinyint(1) unsigned NOT NULL DEFAULT 1, ban tinyint(1) unsigned NOT NULL DEFAULT 0, PRIMARY KEY (profileId), FOREIGN KEY (groupId) REFERENCES pH7_Memberships(groupId), UNIQUE KEY (username), UNIQUE KEY (email), KEY birthDate (birthDate) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1

MySQL said: Documentation

#1067 - Invalid default value for 'birthDate'

**Comment by AndrewCraft-Server** [comment] 2016-08-28 00:31
Wamp server: 3.0.4_x64
apache: 2.4.18
mysql: 5.7.11
php: 6.6.19-7.0.4

**Comment by pH-7** [comment] 2016-08-28 15:39
Hi @AndrewCraft-Server! Thanks a lot for your reply! The error seems very weird to me since `birthDate` with `DEFAULT '0000-00-00',` is correct. To really see why it doesn't accept. Wondering if you have an idea of the error? Maybe you did a research and found why? Because in my case I couldn't find why this is happening..

**Comment by pH-7** [comment] 2016-08-29 19:00
I will reopen it in case you know why that happen with your MySQLServer. Please just let me know ;)

**Comment by AndrewCraft-Server** [comment] 2016-09-01 00:50
I tried it on multiple computers with windows os and wamp they all are failing i am still looking into it tho

**Comment by pH-7** [comment] 2016-09-07 15:01
Very weird! All tests I did on Windows was working well. Indeed, it will be very interesting (and useful!) if you can investigate into it to fix the problem.

Many thanks @AndrewCraft-Server !

**Comment by AndrewCraft-Server** [comment] 2016-09-16 20:02
PH-7 what version of windows are you testing on ? I am on Windows 10 64 bit

**Comment by pH-7** [comment] 2016-09-16 23:04
Windows 10 64 bit. But anyway it's not from WIndows configuration. I would be more likely from your Wamp server configs

**Comment by pH-7** [comment] 2016-09-16 23:05
@AndrewCraft-Server Windows 10 64 bit. But anyway it's not from WIndows configuration. I would be more likely from your Wamp server configs

**Comment by pH-7** [comment] 2016-10-15 18:26
Hi again @AndrewCraft-Server 
Today I tested pH7CMS (latest version) on [Xamp PHP 7](https://www.apachefriends.org/xampp-files/7.0.9/xampp-win32-7.0.9-1-VC14-installer.exe) on Windows 10 and works well as well. If you still have this issue, maybe the best would be to download XAMP (you can keep Wamp and use  XAMP. Not need to uninstall Wamp) . Hope it will work for you now.

**Comment by pH-7** [comment] 2016-10-15 18:29
Could you take 1min to nominate pH7CMS for iDateAwards -> http://ph7cms.com/nominate-ph7cms-to-idate-awards/ ?(This really helps pH7CMS!, thanks for understanding)

Let me know !

Enjoy your weekend!

**Comment by pH-7** [comment] 2016-10-15 18:29
Could you also take 1min to nominate pH7CMS for iDateAwards -> http://ph7cms.com/nominate-ph7cms-to-idate-awards/ ?(This really helps pH7CMS!, thanks for understanding)

Let me know !

Enjoy your weekend @AndrewCraft-Server!

**Comment by pH-7** [comment] 2016-10-16 00:11
I will close it for now. Please let me know if you need ;)
And please also nominate pH7CMS for iDateAwards -> http://ph7cms.com/nominate-ph7cms-to-idate-awards/

**Closed by pH-7** 2016-10-16 00:11 UTC
Labels: bug, Wamp Server, Windows OS
