### ISSUE TITLE
Cannot install - table PH7_Settings doesn't exist

### ISSUE THREAD

**Issue by KeMBro2012** [pH7Software/pH7-Social-Dating-CMS#30] opened 2014-12-21 21:17 UTC
Created a new database and user with all permissions on that database, and I do get tables created:

```
mysql> show tables;
+---------------------+
| Tables_in_ph7       |
+---------------------+
| PH7_Admins          |
| PH7_Games           |
| PH7_GamesCategories |
| PH7_Memberships     |
+---------------------+
4 rows in set (0.00 sec)
```

Apparently, just not all of them...

I get to step 5 in the installation and I get:

```
Error connecting to your database.
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ph7.PH7_Settings' doesn't exist
```

Of course, that means I can't continue installation. Any help?

**Comment by Hostile** [comment] 2016-08-16 11:48
stil not fixed, i getting same error

**Comment by Hostile** [comment] 2016-08-16 12:51
Error connecting to your database.
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dating.PH7_Settings' doesn't exist

**Comment by chrisdpucci** [comment] 2017-04-13 03:46
This is still an issue with the 6.0.9 release. Turning MySQL strict mode off allows installation to complete but it shouldn't be necessary to do so.

**Comment by pH-7** [comment] 2017-04-13 18:15
@chrisdpucci Can you run through your phpmyadmin or mysql command, the following files (in the same order I give you here)

1- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
2- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_DataGame.sql
3- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know if you see any errors from there.

Thanks

**Comment by pH-7** [comment] 2017-04-13 18:16
@

**Comment by pH-7** [comment] 2017-04-13 18:16
@chrisdpucci Can you run through your phpmyadmin or mysql command, the following files (in the same order I give you here)

1- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
2- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_DataGame.sql
3- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know if you see any errors from there.

Thanks

**Comment by pH-7** [comment] 2017-04-14 10:21
@chrisdpucci Please let me know as soon as you can do it, since I am not able to reproduce it on my machine with strict mode. I really need the error from your mysql interpreter so I will be able to fix it.

Thanks

**Comment by pH-7** [comment] 2017-04-17 03:08
@chrisdpucci Please let me know ASAP if you figured out doing what I said?

**Comment by pH-7** [comment] 2017-04-17 11:31
@chrisdpucci Sorry for being that annoying with my comments.. Just wanted to let you that the problem is now fixed: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/4bb8aa7801cb673c833cabadc227d86943bf856a#diff-1b88df76554e8b5c9f766a632d5cd3ba

**Closed by pH-7** 2017-04-17 11:31 UTC
Labels: bug, sql
