### ISSUE TITLE
Adding more genders again

### ISSUE THREAD

**Issue by byyz** [pH7Software/pH7-Social-Dating-CMS#614] opened 2019-08-21 12:07 UTC
Hi there. I have been reading this https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/534 But I cant find this pH7-Social-Dating-CMS/_install/data/sql/MySQL/pH7_Core.sql My webhotel says this file does not excist. Am I doing somthing wrong??

**Comment by Undefined-Variables** [comment] 2019-08-21 12:35
The _install folder is deleted after installation so if you are trying to update an existing site you will have to download the source code again. Once you have downloaded and unzipped it you will find the _install folder.

The .sql files are in _install/data/sql/Mysql/

**Comment by byyz** [comment] 2019-08-21 13:48
Hi and thanks for your answer. Can I edit the file during a reinstallation?

**Comment by Undefined-Variables** [comment] 2019-08-21 13:53
Before the install yes. But it will not have any effect until you make the other changes you need to make. 

If you already have a running site I see little point in doing a total reinstall just to add extra sexes. Do you have PhpMyAdmin installed? This is the simplest way to make database changes. Personally I would make the changes using terminal.

**Comment by Undefined-Variables** [comment] 2019-08-21 13:59
If you are going to do a reinstall I would hold off for a little longer. A update is coming soon and offers a few additional features.

**Comment by polynamaude** [comment] 2019-08-21 14:35
@Undefined-VariablesYou must have a very special version of pH7CMS ! Because if you modify only the database then the only thing modified is the database. It won't offer you more gender type as it doesn't fetch a list of type from the database but those are static.

So this means you have you'll have to edit some code and it gets lost on updates. Unless you patch them every time. Use a Version Control System software like would make it simpler for you as you can do a simple merge.

**Comment by Undefined-Variables** [comment] 2019-08-21 15:35
That is why I said...

{quote}
Before the install yes. But it will not have any effect until you make the other changes you need to make.
{/quote}

You can make changes to the database before making the changes to the code, does not make a difference, think what he is saying is if he can modify the database then install the change is easier as you don't have to update it after installs, I have made lots of changes top my database for future additions that are just coming together now. 

For example, I added a table for crypto currency and made changes to the memberships table to accommodate this, not just btc I have the ability to accept 20 different coins and without having to hold entire blockchains. The changes make no difference until I let the code know they have been done.

**Comment by byyz** [comment] 2019-08-21 15:39
Im totatally new in this world but Im planning to make a dating site. Step by step. So its ok if I have to reinstall a couple of times. At the moment I just have test site with ph7csm installed via softaculous from my webhotel

**Comment by Undefined-Variables** [comment] 2019-08-21 15:41
Good for you mate, thats the best way to learn just going for it :)

**Comment by polynamaude** [comment] 2019-08-21 15:45
@byyz A good start would be to install it by yourself. I have really big doubt that by using automatic installer you'll learn much. By installing yourself, you'd have learned how the install process goes and this would have saved us from needing to explain it to you.

**Comment by Undefined-Variables** [comment] 2019-08-21 15:47
lol I don't use the installer, its not a practical way to do it

**Comment by byyz** [comment] 2019-08-21 15:48
@polynamaude I get your point and will try to do I think 
@ Undefined-Variables Yes I have PhpMyAdmin installed

**Comment by polynamaude** [comment] 2019-08-21 15:50
@byyz Maybe you shall start with a course of programming and get some experience before trying to host a website (and email the world because you get hacked). By the way, watch out for Youtube Javascript hacking because @Undefined-Variables had this problem too.

You'll get the cops at your doorstep.

**Comment by rondlite** [comment] 2019-08-21 15:51
> For example, I added a table for crypto currency and made changes to the memberships table to accommodate this, not just btc I have the ability to accept 20 different coins and without having to hold entire blockchains. The changes make no difference until I let the code know they have been done.

wow you invented a new type of blockchain... amazing..   just wonder what you store since  the world might need it!

**Comment by Undefined-Variables** [comment] 2019-08-21 15:52
You can use the installer for now its a big ask to just expect someone to do a manual install especially when they dont know the code, do a normal install then worry about making the changes afterwards, it will be easy using PhpMyAdmin. I have had my share of issues (learning curves).

@rondlite lol no I am using a service called coinbox! look them up its pretty simple to integrate! And has a nice interface for users too.

**Comment by polynamaude** [comment] 2019-08-21 15:57
@Undefined-Variables **its a big ask to just expect someone to do a manual install especially when they dont know the code,** then what the hell are you doing trying to host a website if you don't know ?

Sorry mister police officer if I ran down the street and broke everything with my car, I'm learning. Oh well there's place to learn and there's also steps in life. You learn to drive a bike before trying a motorbike.

**Comment by Undefined-Variables** [comment] 2019-08-21 16:00
I am not talking about me! Are you still asleep?

**Comment by polynamaude** [comment] 2019-08-21 16:00
@Undefined-Variables There's not much "coding" in the use of installer.

**Comment by byyz** [comment] 2019-08-21 16:01
Thanks for your answers. I will think about this again as it all make sense what you say. I can see if I use the installer I dont get the chance to edit anything during the install

**Comment by polynamaude** [comment] 2019-08-21 16:04
@byyz And every place your are gonna ask will give you the same answer. We don't support Softaculous, we don't know how they deal with the install process so we don't have a clue regarding the settings of your installation.

Do the same on the Joomla support forum and the answer you'll get will be even sweeter than here. Something like... hey script kiddie.

**Comment by byyz** [comment] 2019-08-21 16:08
Hehe nothing is easy in this world :) I will try to install it manually

**Comment by polynamaude** [comment] 2019-08-21 16:08
@Undefined-Variables Does he have something to loose to use the installer and see what it does ? Maybe you shall keep your ideas to yourself as if I look at all you said lately, not much hasn't been either erased by yourself or finished in a "Oh I'm sorry, I was a big light headed, too fast, short tampered, etc".

You are the one opening endless issues for "sweet fuck all" and closing them soon after, adding not much more than empty words.

You say to the guy, no don't use the installer if you don't know what's the code ??? What ? Where's the need to know the source code to use the installer. Could you make a minimum effort ? You are burned and will stay as such until you grow up and show it. And this hasn't been done.

**Comment by polynamaude** [comment] 2019-08-21 16:09
@byyz Even more when you just think about making an easy buck in the end but forget that it's not a sand castle.

**Comment by byyz** [comment] 2019-08-21 16:12
Its actually bcuz I got a lot of spare time. I would like to try to learn something new and my plan was to keep the free for use. So I just ran into this issue about gender

**Comment by Undefined-Variables** [comment] 2019-08-21 16:16
@polynamaude I think we are talking different languages or you are not reading what I am saying. I said use the installer you said hey make it a challenge and do without it! 

I'm off for now anyway I have an important family diner this evening. Then im going to get some sleep! 

Have a look at my site if you like feedback@ {mysite}.com password is password :) 

Laters...

**Comment by polynamaude** [comment] 2019-08-21 16:25
@Undefined-Variables Say "Hi!" to your parents and don't forget to brush your teeth. And think about getting a real job.

**Comment by Undefined-Variables** [comment] 2019-08-21 17:12
Thank you for being nice, it suits you :)

**Comment by byyz** [comment] 2019-08-22 10:07
Hey Guys. I manage to install ph7cms by myself and before that I did the changed I wanted to the sql file. So far so good :) thanks for your help. 
After the install are there things I should do? Change permission to folders etc?

**Comment by polynamaude** [comment] 2019-08-22 11:23
@byyz 
I'd say... read the manual so you don't ask question already answered !

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki
http://ph7cms.com/doc/
http://ph7cms.com/blog
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
https://ph7cms.com/doc/en/install

The best thing I can suggest... Don't do like @Undefined-Variables ...
example : https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/615

Accusing people of thing that didn't happened or that you don't understand.Even more when it's the person who helps you out !

**Comment by polynamaude** [comment] 2019-08-22 11:35
@byyz You can access your database through the CLI and send direct SQL command by using the mysql command from shell.

**Comment by byyz** [comment] 2019-08-22 17:15
Thanks :)

**Comment by Undefined-Variables** [comment] 2019-08-22 17:16
> @byyz Maybe you shall start with a course of programming and get some experience before trying to host a website (and email the world because you get hacked). By the way, watch out for Youtube Javascript hacking because @Undefined-Variables had this problem too.
> 
> You'll get the cops at your doorstep.

Yeah I have been hacked so many times its getting embarrassing, at least the last few times have not cost me anything. When you loose 22k its more than embarrassing it hurts like a punch in the face! But that peanuts  compared to what the scum took of me... 785btc just think how that felt!!!

**Comment by polynamaude** [comment] 2019-08-22 17:22
@Undefined-Variables Hey dude ! We don't believe shit about what you say....
You forgot that people are not born yesterday.... Stop trying to show that you are a big guy when you ain't and leave other alone.

There's no problem to learn by trial and error. The problem is when you become a pain in the ass like you are, don't take the time to listen to what others have to say and go on with furious rampage. I told you from the beginning how it was going to end and you did total opposite. You continued asking unrelated questions, talking about things you don't know, etc.

Get a job or go back to school but get a life.

**Comment by polynamaude** [comment] 2019-08-22 17:25
@Undefined-Variables One day you talk about thousands of dollars but not long ago you didn't have enough to pay simply for a domain name (about 10 euros). So please, don't take people for dumb. Maybe this works with people around use because they are just fed up with your shit and don't feel like getting into useless arguments.

You have nothing more than a computer that is trying to host a dating site from your home. With proof, you talked about taking the hard drive out and sending it by courier. That's impossible when you are using managed hosting in a data center.

Now go on !

**Comment by Undefined-Variables** [comment] 2019-08-22 18:13
Start by googling my real name, you will see I am not talking shit! I was only released from jail on the 28th Aug 2018 after serving 5yrs for 3 counts of supplying a class A drug, 2 counts of importation of a class A drug and  one count of procession of a firearm.  

I ran 3 accounts on SR Bitcoins, Happyman and RichieRich here are the links on antilop.cc (st.exo's backups)

https://antilop.cc/sr/vendors/c536b90105.htm
https://antilop.cc/sr/vendors/ffef1b6754.htm
https://antilop.cc/sr/forum/srvendor/SR_Vendor_profile_3247.html (this one is only forum as my account was in vacation mode when backup was taken)

I was first arrested 2 days after Ross and the took 785btc (worth £71 each then) £40.000 in cash and £37.000 from my bank account! I have a piece of  paper as a receipt. They also took £20.000 worth of electrical equipment, laptops, iPad's, servers, pc's basically anything with a hard drive and my IPhone, again I have all the paperwork! I spent the following 2years on bail as they had a huge case to build, I was then charged and agreed to go guilty to 7 of the 11 charges and after all was said and done I was given 5years in A cat jail.  

I gave my co defendant 7 coins to store with his 1000's a day before being sentenced, so he could give them back upon release, they were worth £375 each, while we was inside they rocketed to £11.000 each and after release he won't speak to me and has vanished so never seen the coins again.

I can prove every single part of it and could tell you stories that have never been told before about that time. This is one thing you can't tell me I'm lying about, I had money once lots of money but lost it all! 

Yes I'm penniless now but I've only been free for a year and found a job and held it for 7months but was let go due to lack of business, not my fault... You try to get a job with my record, its almost impossible!

**Comment by polynamaude** [comment] 2019-08-22 18:17
@Undefined-Variables What the fuck don't you understand ? YOU ARE OFF TOPIC stop bothering people. Stop trying to convince people. BYE

**Comment by Undefined-Variables** [comment] 2019-08-22 18:20
Dont give a shit you called me a liar and I'm not having that!

**Comment by Undefined-Variables** [comment] 2019-08-22 18:22
BYE

**Closed** 2019-08-22 18:36 UTC
