### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myname.PH7_Settings' doesn't exist,

### ISSUE THREAD

**Issue by herculesnetwork** [pH7Software/pH7-Social-Dating-CMS#162] opened 2018-01-01 22:43 UTC
I am trying to install pH7-social-dating and 3 days I try everything, and already tried on several servers, VPS, and I never can, already tried to create databases with several systems, via sql console, via phpmyadmin, via vurtualmin, and always gives, logically, always with all the privileges, I am accustomed and install and work with CMS.

 But this particularly I can not even install, I have very well configured servers by hand, **with ubuntu 16.04.1-64bits, nginx 1.10.3, msql-5.7, php7.0-fpm**, and I can never install it because it says that a file is missing from your installation wizard: **Error connecting to your database.
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myname.PH7_Settings' doesn't exist,** 

Because the installation script can not create this file, and how do I create it?

**Comment by herculesnetwork** [comment] 2018-01-02 01:03
And when I saw a hint to put the strict mode off, I followed and hints and I got another error:

**Error connecting to your database.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'**

**Comment by pH-7** [comment] 2018-01-02 10:34
Hi @herculesnetwork!

The second message is caused because you reinstall it on the same database with the same DB prefix (so, you get duplicate errors since previous tables are already there).

**Comment by pH-7** [comment] 2018-01-02 10:35
@herculesnetwork Concerning your first message,
can you create a new database through your phpmyadmin and run the following files (in the same order) with strict mode set to on.

* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know if you see any errors from there.

Thanks

**Comment by herculesnetwork** [comment] 2018-01-02 17:18
yes the second message was because I fumbled and tried to do a new install inside the same database, and I always delete it and create another between one try and another, and I forgot to delete before trying again to install. thanks for reply.

**Comment by herculesnetwork** [comment] 2018-01-02 17:57
yes I still have the same error, I was disconnecting the strinct mode via sql console, it is temporary after restarting the mysql service it returns to the default on, ( `set global sql_mode='';` ), I restarted mysql, so I create a new database, with `utf8_unicode_ci` - and I pasted these commands into sql in the new database via phpmyadmin, then following all of these permission tips: `https://ph7cms.com/doc/en/inst` I still have the same error, ( an addendum, when I am giving the permissions, I get two folder errors do not exist: )  `chmod 777 /home/meets2/public_html/_repository/upgrade/*
chmod: cannot access '/home/xxxxxxx/public_html/_repository/upgrade/*': No such file or directory
` it must be because this file does not yet exist. my error screen: [](https://imgur.com/a/3jaMR)

**Comment by herculesnetwork** [comment] 2018-01-06 00:00
???!

**Comment by pH-7** [comment] 2018-01-07 12:47
For now, I'm still not able to reproduce your error. For now, I suggest digging on StackOverflow and others looking for a solution for your case. 

Please keep this thread updated as soon as you get news.

**Comment by pH-7** [comment] 2018-01-09 19:05
Hope that helps @herculesnetwork  Sorry again about that ;)

**Comment by herculesnetwork** [comment] 2018-01-09 20:06
Ok. Thanks.

**Comment by pH-7** [comment] 2018-01-29 09:31
Thanks! I will close it for now

**Closed by pH-7** 2018-01-29 09:31 UTC

**Comment by pH-7** [comment] 2018-01-30 01:35
Hi again @herculesnetwork 
I think I found the reason of your problem
https://stackoverflow.com/questions/2659684/why-my-tables-names-are-converted-into-lowercase-in-phpmyadmin

If you check your tables, there are chances that your table names were converted to lowercase. This won't work since the table names are different. You will have to disable that option. See my link above.

Hope that helps! Again, have a great day! 😺
