### ISSUE TITLE
updater in admin panel

### ISSUE THREAD

**Issue by zeerprettiggestoord** [pH7Software/pH7-Social-Dating-CMS#207] opened 2018-05-22 19:34 UTC
Would be great if you could make an updating system for admins that downloads and installs the newest updates. 
On a different note: Keep up the good work. Love what you have been doing!

**Comment by polynamaude** [comment] 2018-05-22 21:07
Hi pH,

Have you ever worked with gitHub API? This gave me the idea of making a script that is triggered by the publishing of update and would indicate on the admin side that updates are available.

Le 22 mai 2018 15:34:20 EDT, zeerprettiggestoord <notifications@github.com> a écrit :
>Would be great if you could make an updating system for admins that
>downloads and installs the newest updates. 
>On a different note: Keep up the good work. Love what you have been
>doing!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment] 2018-05-23 08:41
Hi @zeerprettiggestoord 

Thanks for the suggestion. I was working on something like that, but it isn't stable at the moment with the latest versions .

So, you will still have to do it manually.

- Make a backup of your whole website (and also your database if you are very careful)
- Run the correct SQL upgrade file (if there is one for the wanted version). e.g. https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_repository/upgrade/12.1.0-12.6.0/data/sql/MySQL/upgrade.sql in order to update pH7CMS from 12.1.* to 12.6.0
- Replace all files with the new ones you just downloaded (e.g. from pH7CMS-12.6.0.zip archive)
- Then, if you did modifications, put back your custom modifications from your backup in the new files

Really happy if you appreciate the software 🎉! Thx!

**Comment by pH-7** [comment] 2018-05-23 08:44
Hi @polynamaude 

No, not really, but this can also be a great idea, indeed! I haven't thought about it

**Comment by polynamaude** [comment] 2018-05-23 20:22
Hi,
Shouldn't be too hard using Webhook. I'll take a look.

PM

Le 23 mai 2018 04:44:14 EDT, "♚ PH⑦ Soria ♛" <notifications@github.com> a écrit :
>Hi @polynamaude 
>
>No, not really, but this can also be a great idea, indeed! I haven't
>thought about it
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391269340

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment] 2018-05-23 21:49
That's great PM :+1:  Let me know if you need :)

**Comment by polynamaude** [comment] 2018-05-23 21:55
I did 4 years of psychology and still don't understand how can people think that because it's open source and free that we should also customize, give support and add requested features, all free and at the same time pay the rent and grocery.

Thx

Le 23 mai 2018 17:49:07 EDT, "♚ PH⑦ Soria ♛" <notifications@github.com> a écrit :
>That's great PM :+1:  Let me know if you need :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391507671

-- 
Polyna-Maude R.-Summerside

**Comment by zeerprettiggestoord** [comment] 2018-05-23 21:59
Ph-7 was open for suggestions. I gave a suggestion. He is entitled to do nothing with it or do something with it. If I could I would donate. When I am able I will. That is how much I like the software.

**Comment by polynamaude** [comment] 2018-05-23 22:22
Hi !
I don't think I talked about you, if you feel that it does get to you then I can't do anything about it.

But if you want to do something then I'm sure there's a way that you can collaborate. Be it that you do PHP coding or other. Even small donation can be great to get, considering that it's this software that allow you to make money.

Le 23 mai 2018 17:59:44 EDT, zeerprettiggestoord <notifications@github.com> a écrit :
>Ph-7 was open for suggestions. I gave a suggestion. He is entitled to
>do nothing with it or do something with it. If I could I would donate.
>When I am able I will. That is how much I like the software. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391510135

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment] 2018-05-24 04:02
What language are you doing?

Le 23 mai 2018 18:25:33 EDT, zeerprettiggestoord <notifications@github.com> a écrit :
>@polynamaude please accept my apologies. I actually am in the process
>of contributing. Im no coding expert like you guys but am working on a
>translation of the software. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391516598

-- 
Polyna-Maude R.-Summerside

**Comment by zeerprettiggestoord** [comment] 2018-05-24 11:30
Im doing the Dutch Language.

**Comment by pH-7** [comment] 2018-05-24 13:38
That's great @zeerprettiggestoord! :tada: 

This should already help you https://ph7cms.com/doc/en/how-to-translate-to-another-language (it's a great start to translate the software into a new language :smiley:)

Finally, https://github.com/pH7Software/pH7-Internationalization is the repository where all translations are stored. There is already a Dutch translation , but it hasn't been updated for several years, so it's probably better that you retranslate it from scratch (from [global.pot](https://github.com/pH7Software/pH7-Internationalization/blob/master/global.pot)), (except if you already started from it..).

P.S. You are probably from the Netherlands then. I'm from Belgium, but don't really speak Dutch...that well.. :D

**Comment by polynamaude** [comment] 2018-05-24 14:06
Hi !
I don't know what operating system you use but if you need help finding a editor for the translation then just tell me. I'm on Linux but I know software for Windows and for Mac it's possible to "homebrew". But check the docs pH gave as link because there's probably such information too.

Happy writting

Le 24 mai 2018 07:30:04 EDT, zeerprettiggestoord <notifications@github.com> a écrit :
>Im doing the Dutch Language. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391681052

-- 
Polyna-Maude R.-Summerside

**Comment by zeerprettiggestoord** [comment] 2018-05-24 14:46
Im using the global.pot to start from scratch.
Program I use is Poedit.

**Comment by zeerprettiggestoord** [comment] 2018-05-24 14:50
but to stay on topic.... PH-7 has knowledge of wordpress, 
Is it an idea to reverse engineer the way they do it?

**Comment by polynamaude** [comment] 2018-05-24 15:28
I have no idea what you're talking about but I could be pretty sure that there's no "reverse engineer" of Wordpress ! Could you either justify your affirmation or give more information about what's behind your mind.

A bit insulting there but not the first time I see people thinking that OpenSoufce means to get piece of code from other people and re-use them putting our copyright.

And if the fact that WordPress would use the same type of file (PO) then it would be good to make some research before just saying stuff because pH7CMS is simply using a international library (GNU Iconv) that's used in many thousand software.

PM

Le 24 mai 2018 10:50:59 EDT, zeerprettiggestoord <notifications@github.com> a écrit :
>but to stay on topic.... PH-7 has knowledge of wordpress, 
>Is it an idea to reverse engineer the way they do it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391743393

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment] 2018-05-29 22:32
Closing it by now, since I won't have time to build such a system right now, and the Upgrade wizard already exists in pH7CMS. 
Anyway, if anyone is interested to realise this suggestion, just do it and open a PR. Nothing really complicated. 
Thanks

**Closed by pH-7** 2018-05-29 22:32 UTC
Labels: feature, suggestion

**Comment by polynamaude** [comment] 2018-05-29 23:09
Good ! I took a look at the gitHub webooks and we could at least say when a new one is available. I'll get back with a PR when done.

Nice to remind people to contribute too ! I made a contributor guide / issue / request for help. What about I add to the doc ? Or do you prefer on gitHub as wiki?

PM

Le 29 mai 2018 18:32:23 EDT, "♚ PH⑦ Soria ♛" <notifications@github.com> a écrit :
>Closing it by now, since I won't have time to build such a system right
>now, and the Upgrade wizard already exists in pH7CMS. 
>Anyway, if anyone is interested to realise this suggestion, just do it
>and open a PR. Nothing really complicated. 
>Thanks
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-392969230

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment] 2018-05-30 07:21
I'll add a thing about software devrlopment and general contribution  culture, it's also about treating others like you want to be treated.

Don't call out blaming errors unless there's really one, in doubt always ask.

Take care about the "great ideas", most of the time it's alreafy thinked about. If you just used a day old new option and think that something is wrong. Unless it's a typing mistake, it's more than probable that the developper already used the software more than you. So maybe you just miss how to use. Again asking is a better solution.

Never forget that most people invest time into software without nothing in exchange so when you get people that complain about things that aren't really worth it or that are a code 3 (the problem is 3 feet in front of the screen). In the end, it will play on your attitudes.

Try re-install software.

Good place is important. You don't talk about problem transferring using ftp on a network driver page, don't ask for help with your hosting server on a operating system page and don't ask things out of your technical ability. For example about using php library if you don't know how to do basic php or at the level needed. Don't ask on a CMS page how to make a template if you don't know HTML or what a "for loop" is.

And the best I can say is to learn basic PHP as it's a pretty literal language so it's easy to read. Read the sources and read manuals, always search the documentation before asking. Nothing more frustrating than answering question that you wrote a book about !

If you doubt my words then go check how user rating is done on StackOverflow.

In the end, say thanks when a answer helped out.

Sincerely,
PM

Le 24 mai 2018 11:36:50 EDT, zeerprettiggestoord <notifications@github.com> a écrit :
>No, I meant that if you run a WordPress website it will give you a
>heads up about a new version.
>With the press of a button, it downloads the new upgrade, switches to
>maintenance mode and unzips the zip file and installs the new version.
>if the database needs to be upgraded it will also prompt that it needs
>to get upgraded.
>
>Maybe you could write something like that in your own code.
>Don't want to disrespect you guys who know how to code.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/207#issuecomment-391760093

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment] 2018-06-22 19:28
@zeerprettiggestoord  If you do want books about PHP then I can send you some by email (english). You can look at OpenClassroom that is pretty good.

By the way, there's nothing of anger in what I did tell you but if you ever go further then people won't tell you many time. Go look at the Linux Kernel Mailing List, KDE Gnome or simply Joomla.

PM

**Comment by zeerprettiggestoord** [comment] 2018-06-22 19:45
@polynamaude I have enrolled into 4 courses on udemy. They have this sale
at this moment. First one is php for beginners also handling mvc and object
orientated programming with building a cms as a project..  Got my work cut
out for me. Thank you for your kind offer.

Op vr 22 jun. 2018 21:28 schreef Polyna-Maude R.-Summerside <
notifications@github.com>:

**Comment by polynamaude** [comment] 2018-06-22 21:43
@zeerprettiggestoord  May I warn you that it may be wiser to look with your local university/community college for adult continuing education about computer courses offered either part time or distance learning than to pay somewhat high fees (in some case) for private MOOC (Massive Online Open Classes).

For sure it's better than simply being alone but you can get all needed support and help from StackOverflow and alike. 

Often MOOC will do fast track and jump over essential needs to get results that sell good (abilities to make a project). For example they'll sell you that you'll learn design pattern but in the end you learn one or two of them but not the "boring but needed" under the hood to understand the real concept. They may say they teach Object-Oriented programming when in fact they'll only really show object based language. Two whole different concept, for example you can use C++ (object language) but your code look mostly procedure based.

You've talked about WordPress, search for "Object programming in PHP with WordPress PDF" it's a free 40 pages book. In the first page we explain that WP uses lot of global variables and is mostly procedural because it was designed for PHP 4 and it wasn't having the object extension that PHP 5 started to get.

Pierre Henry reminded me this week about that when he told me to "extract till you die" as one of the rules is one method=one thing done.

Anyway, good luck for programming in PHP. The MOOC may push you to progress as you see average learning time.

Also adult education in college and university is different from admission to bachelor's degree and alike. There's not much requirements other than to send your curriculum and a letter showing interest. There's often many "introduction" courses. For example you may get "Introduction to object programming with Java" or "Introduction to data warehouse with SQL".

If you need something you can contact me by email as this is for pH7CMS.
