### ISSUE TITLE
PH7CMS 16.0.0

### ISSUE THREAD

**Issue by coucoudan** [pH7Software/pH7-Social-Dating-CMS#857] opened 2021-02-26 11:31 UTC
**Describe the bug**

A problem with accessing profiles when you are not logged in and all the privacy options are enabled in the user configuration.  PH7CMS v16.0.0

**To Reproduce**

Unauthorized URL: https://domain.ltd/@username 

1. Go to the URL https://...../@username 
2. redirect to page not allowed when not logged in. 
3. the page is visible regardless of the options chosen in the user's privacy settings. 

**Expected Behavior**

If the options in the user configuration are private, access must be blogged to unregistered visitors. 

**Screenshots / Screencasts**

With "/@webmestre" it redirects to the "/super-profile/18" folder 
and the full profile appears.

**Comment by polynamaude** [comment] 2021-02-26 15:05
There's so many bug in this software that all the users I know who tried it, they've all went to something else after a week or two, only one guy tried fixing them in the long term but he didn't get support from the project manager. And because the project manager is better at complaining about space missing in source code than accepting contribution, it makes this project quite useless.

But at least, the source code is beautiful !

**Comment by polynamaude** [comment] 2021-02-26 15:05
The system break when you reach a certain user limits...
There's a truckload of bug

**Comment by coucoudan** [comment] 2021-03-08 11:37
The worst bug is the pictures album that works well in developer mode but not at all in production mode. When searching for Google, there are sites on the promotion of PH7cms than on real sites in production. 

It's horrible this software all done in MVC objects everywhere in the script. The settings that walk half. What is this script there.

Do not good script.  

It is beautiful but not functional. 

You are right pornamed.

**Comment by coucoudan** [comment] 2021-03-08 11:48
I would like to use free software and walking well.

**Comment by polynamaude** [comment] 2021-03-08 16:29
@coucoudan I think you're a French dude...
In English we don't say "walk well" (marche bien) but we say "work well" (fonctionne bien).
Software don't walk around the place...
At least, you didn't loose too much time with this software.
Yes there's lot of backlinking too, some older version (before me and a friend, discovered, made public and confronted the author of the script) used to send links to the developpers website everywhere.
It was making publicity for the developper's website.
I used to participate in this software development but I got away when I saw all the bad stuff around.

**Comment by coucoudan** [comment] 2021-03-09 01:33
I will send a blame to Google Translation. A joke.

You are right

french to english google.  :-) 


> 
> @coucoudan I think you're a French dude...
> In English we don't say "walk well" (marche bien) but we say "work well" (fonctionne bien).
> Software don't walk around the place...
>

**Comment by polynamaude** [comment] 2021-03-09 02:05
@coucoudan If you want something nice...
https://una.io/

A bit expensive...

You also have

https://www.opensource-socialnetwork.org/
https://www.humhub.com/en

A good text
https://opensource.com/article/19/9/open-source-social-networks

Also you can use Joomla with either Community Builder or JomSocial.
Or simply Joomla with some social login extensions (free).

Also there's WordPress with BuddyPress

**Comment by pH-7** [comment] 2021-05-08 23:00
Hey @coucoudan, since you didn't get back to me, I assume the problem is fixed. I'm closing it by now. If it isn't the case, please feel free to open a new issue. Thank you! 😺 [Pierre-Henry](https://github.com/ph-7) 🤖

**Closed by pH-7** 2021-05-08 23:00 UTC
