### ISSUE TITLE
Invalid coding 

### ISSUE THREAD

**Issue by marketing720** [pH7Software/pH7-Social-Dating-CMS#442] opened 2019-02-16 00:13 UTC
Certificate for SSL can not be applied as all the reference links are coded with http and no coding for https - any workarounds available ?

**Comment by pH-7** [comment] 2019-02-16 23:56
If you installed pH7Builder (pH7CMS) with http, then moved to HTTPS, you will have [to clear the caches](https://ph7cms.com/doc/en/how-to-clear-caches) in order to regenerate the URLs and get them with HTTPS. Go to your Admin Panel, -> Tool -> Caches -> Caches Manager.

FYI, the software automatically checks the protocol (http/https).
This is done is your `_constants.php` file (around line 23) located in the root folder after the installation of the software has been done.


Let me know if this helps.

Have a great weekend anyway :tada:

**Comment by pH-7** [comment] 2019-02-16 23:57
Finally, do you mind to Star the repo @marketing720?
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by marketing720** [comment] 2019-02-17 00:38
Thank you sir - how do you get the phone app to work or do you have any documentation or a paid service I can use to finish it up? 
    	
    	

    	Get Outlook for iOS
    
  




On Sat, Feb 16, 2019 at 4:25 PM -0800, "♚ PH⑦ de Soria™♛" <notifications@github.com> wrote:












Assigned #442 to @marketing720.

**Comment by pH-7** [comment] 2019-02-17 08:00
Hi @marketing720 
Can you please create a new "Issue" if the problem is different. This helps to keep each thread tiny and avoiding confusions in there. **Finally, do you mind to Star the repo?**
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment] 2019-02-19 05:07
@marketing720   **Finally, do you mind to Star the repo?**
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment] 2019-02-20 06:16
I will close this one by now @marketing720. Please let me know if there is any more issues with https (if it's still the case...).
Thanks. Enjoy your day 🎉

**Closed by pH-7** 2019-02-20 06:16 UTC
