### ISSUE TITLE
Issue with changing password and loging into admin panel

### ISSUE THREAD

**Issue by VJ55** [pH7Software/pH7-Social-Dating-CMS#192] opened 2018-03-30 21:47 UTC
Hi,
I installed ph7CSM 12.1.2 and had no problem loging into the admin panel the first time, but when I tried to change the password I was getting a message that my original password was not correct. After that I logged out from the admin panel and tried to login again but I was getting similar message that the user name , user e-mail or the password are not correct.
I will appreciate if someone can help in resolving this issue.
Thanks,
VJ

**Comment by pH-7** [comment] 2018-03-31 01:54
Hiya @VJ55!

I couldn't reproduce your issue. Did you install it with Softaculous or downloaded from Sourceforge/Github?

If you couldn't change your password. The password is still the previous one. Are you sure caps lock isn't on (or when you installed pH7CMS)? Please make sure there is no type. Otherwise, ask to reset your password -> `your-website.com/forgot/admin123`

Finally, did you edit your username before log out?
<img width="872" alt="screen shot 2018-03-31 at 02 12 02" src="https://user-images.githubusercontent.com/1325411/38158410-c8d75e48-348b-11e8-8704-3ac8bf3088bd.png">

**Comment by VJ55** [comment] 2018-03-31 12:37
Thanks pH-7 for the advise, I was able to change the password after I used the new (temporary) password that was sent by e-mail and now there is no problem with logging into the admin panel. 
However the mystery still remains why after the initial log in into the admin panel I was not able to change the password nor to log in a second time into the admin panel. In both cases did not recognize my initial password. The installation was done with softaculous and after I post the issue I re-installed the software again , but the issue remained. There was no typo , no capital letters and I didn't change the username.
Thanks for your help,
Best regards,
VJ

**Comment by Povertyhill1** [comment] 2018-03-31 13:34
I seem to have the same or similar problem. I have installed Version: 12.1.2 Version Name: PHS
Version Build: 1 Release Date: 03-20-2018 using Softaculous. I kept having trouble logging in more then once. I would login add another admin to be safe and logout. Could never login again using the default user name password email. Would uninstall and re-install and would do the same thing. If someone has an idea please let me know as I can't even test it to see if it is the software I want to use. Thanks

**Comment by pH-7** [comment] 2018-04-07 16:51
Thanks @VJ55 @Povertyhill1 
Probably an issue on Softaculous side. Did you use the "random password generator.."
Was it only an alphanumeric password? Or your password had various unusual characters..?

**Comment by VJ55** [comment] 2018-04-11 02:05
I didn't use the "random password generator" , I have selected my own password and it was a combination of letters, numbers and symbols

**Comment by polynamaude** [comment] 2018-04-11 04:38
As it is noted for others issues of the same kind we'd suggest you do a "standard" install using either the tarball available on Sourceforge or by download a copy of the last branch on the repository here.

It's pretty hard for us to answer any question relating to installation when it's done using Softaculous as it's out of our knowledge how do they actually interact with the installation script and transfer your password onto the installation, same for all others options they may offer (if any).

So I'd suggest that you follow the instructions for the installation. It's pretty easy to do and it will only give you a better understanding of how the system works. It's what I do for all the installation that I have to do, including the ones that Softaculous does quite good like  Joomla/Wordpress. It gives me a complete control over what's done and most of the time I get setting at installation time that would have been more complicated to change later on. For example softaculous doesn't give you the real feedback when testing for the requirements but only test against what they have in there database. Some options like output buffering may not be set properly.

If you're a paying customer for Softaculous then I'd suggest you contact there customer supports.

What you are talking about is a Softaculous problem much more than something related to the CMS. They choose to sell a product that make easy installation of other free software and it stop there.

**Comment by pH-7** [comment] 2018-04-14 05:47
Hey @VJ55 If you get the chance to reinstall it through Softaculous, could you try with only letters and numbers (without any symbols). ie `greatcity123`?

Like what @polynamaude said, if you really want to install pH7CMS with Softwculous, maybe contact them saying the problem.

**Comment by Prinz234** [comment] 2018-04-22 07:41
"If you login to Admin Panel for the first time, make sure you logout within 10-minutes, then login again. This way, the system recognizes you as a bona-fide Admin. But if you login and stay for hours, the system will eventually log you out, as if you broke into the Admin Panel by chance, so it rejects your Password when you want to login again. That's where the whole problem starts."
I had this issue for weeks before I discovered this solution, I think it's an inbuilt security measure.
I experienced this problem via Softaculous platform. But this will help anyone with similar issue out.

(I WANTED TO INSTALL pH7CMS DIRECTLY BUT MY FILE STOPS HALFWAY WITH AN ERROR MESSAGE [MLSD] ON FTP CLIENT/VOYAGER, STILL HOPE I COULD FIND A WAY OUT. ANY HELP PLEASE?

**Comment by pH-7** [comment] 2018-04-22 13:03
FYI, I contacted the Script Packaging team of Softaculous saying this issue. They will hopefully fix it soon.

**Comment by polynamaude** [comment] 2018-04-22 13:31
If you can't use one ftp clien then change, there's many.

Archive upload problem aren't related to the CMS.

**Comment by polynamaude** [comment] 2018-04-22 13:35
@Prinz234 Have you ever had the idea of asking the guy who wrote this software about your 10 minutes-logout on first time admin user? Have you looked into the source code to find out if what you said is true ? Maybe it's more complex (or less).

**Comment by Prinz234** [comment] 2018-04-22 18:29
@polynamaude  Thanks for your response.
I have tried Filezilla too, but still not working. Any suggestions?

As for the 10-minutes logout, menh I don't know about source codes, I just said what helped me out after weeks of not being able to login to My Admin Panel.

**Comment by polynamaude** [comment] 2018-04-22 18:45
If you can't use a FTP Client, either to configure or find one by yourself then maybe there's some learning to be done before trying to host a web server.

Instead of making affirmation that don't say much, as long you don't know how and why a procedure work. It's not because something worked for you that it will be working for others. Even more as I've told you many time but don't seem to understand, if we don't get information about your hosting environment (detailed). It won't be possible to figure out the context of your installation, so won't be of any help.

Good luck!

**Comment by Prinz234** [comment] 2018-04-23 07:25
@VJ55 This issue has been resolved by Softaculous, they sent me a mail and I can confirm it works now. But the Admin Password ratification affected the User Profile Background Image display, it doesn't work any more. I hope they will sort out too.

**Comment by Prinz234** [comment] 2018-04-23 07:30
@polynamaude 
I learn through practice, and that's what am doing right now.
Thanks anyways.

**Comment by polynamaude** [comment] 2018-04-23 09:37
Maybe you should also learn the difference between knowledge and "playing around". When the only thing you do is go by try - error loop and add a bit of luck. You should be enough honest with yourself to know your limits and others too.

At first, I've offered to help you out but nicely explained that to do so, I'll need that you provide some basic unformation. You had the belief that it wasn't needed so you ignored.

At second, if I asked you if you did confirm your belief with some fact. It's simply because you've had a chat with the person who did write this software (seem to be the good person to ask).

And at third, you're opening an issue about a software when you don't have the basic knowledge to do so. It's basicly like complaining that a word processor software don't work properly with your number keys but don't know what the "num lock" key does.

If it's out of your ability to install manually this software (or any other CMS) then you won't be able to do much once you completed your installation is done. As customising will require in-depth knowledge of CSS, HTML and PHP, plus some server admin.

There's stuff in life that is beyond the read of a click of mouse and that need more than just "playing around". Even like you said, you learn from what you see. There's much out of reach of your mind and that does constitute what you haven't learned but that can influence you.
For example the security procedure of your hosting provider and their usage of different heuristic to treat interaction as normal and not. The differences in the way operating system and firewall will treat the caching request made by using "curl". And much more !

With the cooperation you offer and your ability to operate a system (simply to ask me a FTP client when you can find many by yourself and learn how to use it). I don't see how it's possible to consider your problem as a "issue" with the software versus the simple fact that on some installation there will be some need to make system configuration for the web instance. And the proof is that you never answered the question if your system was online and live when you said it worked and "poof". As you may know, it is possible for badly isolated hosting instance to contaminate each other when one of them get compromised.

Maybe you just wanted attention and didn't really want to get that solved. Always easier to keep our idea that something is wrong than to learn that the problem start with ourself !

**Comment by Prinz234** [comment] 2018-04-23 10:12
@polynamaude mehn all I could see are insults than correction. What does getting attention has to do with asking simple questions about stuffs one doesn't understand. And if you call what am doing "playin around", well that's your opinion. I didn't know I will meet you here before coming on board, and I will get through whatever obstacle I meet on my way to achieving my goal.

**Comment by pH-7** [comment] 2018-04-23 18:06
Good news everybody! 🎉 

I got an answer from Softaculous

> Hi Pierre,
> Thanks for letting us know about issue. I have checked and on second attempt of Login through Softaculous does not work. 
> Earlier we used to pass cost 14 in password_hash method. So after first login script used to update password hash in DB and due to which user can't login with same password. I have changed cost to 12 and it seems to be working fine now. I will release the package with changes ASAP. Will notify you once its launched.
Even in future if you get any issue regarding Softaculous installation the feel free to mail me. We will look into immediately. 

So, the problem was caused because the password cost they set during the installation was different than the default one set on [pH7CMS](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Security/Security.class.php#L29)

**Comment by pH-7** [comment] 2018-04-23 18:06
I will close that one since the problem from this topic is now solved!

**Closed by pH-7** 2018-04-23 18:06 UTC
Labels: bug related to softaculous

**Comment by tuntoy** [comment] 2018-05-15 09:54
My web hotsting has softaculous installer which install the pH7CMS 12.1.2 version i did not change the password i left it like thinking when i  log in then i can change it 
![for dating complat](https://user-images.githubusercontent.com/9052165/40050093-6124a62c-582e-11e8-8f25-63bd8c300268.png)
but my problem is i tried to login to the admin panel but i can see a flash message says "log in first please what is the problem or what can i do

**Comment by pH-7** [comment] 2018-09-06 09:34
@tuntoy This error looks to be session issue... Have a look to my answer on this ticket: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/215#issuecomment-395602193 (that person had the same problem than you).


P.S. Next time, please create a separated ticket, since this problem is different than the initial one.

**Comment by pH-7** [comment] 2018-09-06 09:36
@tuntoy Have a look here: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/275#issuecomment-414920173
