### ISSUE TITLE
top menu

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#458] opened 2019-02-27 03:30 UTC
- First time you log in and land on your own profile and press “people, photo, video and forum” on top menu it will open a new window but if you click on anything in the new window it works fine. So there is only a problem on the first page when you log in how to fix it so it will open in same window

**Comment by pH-7** [comment] 2019-02-27 04:58
Not sure I have this problem. Did you do  any changes in there?
Can you be more specific please. I'm not also too sure to understand it 100%.
You could screencast it and upload it on Youtube. That will make things easier to understand.

**Comment by samit78** [comment] 2019-02-27 05:13
let me explain more specific
lets say profile name sam login with his email and password from website
once login you can see top menu bar .. search |photo 
when click on this menu links open in new window

instead open in new window i want all links open in same window

**Comment by kevinbkk** [comment] 2019-02-28 21:42
> let me explain more specific
> lets say profile name sam login with his email and password from website
> once login you can see top menu bar .. search |photo
> when click on this menu links open in new window
> 
> instead open in new window i want all links open in same window

I had this issue before, but then I reinstalled the script again and it fixed by itself. I really couldn't figure out why that happened. Let's see, hope it not happen again.

**Comment by kevinbkk** [comment] 2019-03-04 18:23
I just find out that your issue is very serious and it is related to database or caches. Whenever something goes wrong, all the top menu links or some opens in new window. That's so weird. A solution is to clear caches. (Not browser caches, only your script cache).

**Comment by polynamaude** [comment] 2019-03-05 01:49
@kevinbkk Cache issue **_or_** database issue are two very different thing. As soon you modify any template then you'll need to clear pH7CMS caches, same if you modify most options in the back-end (administration).

I can hardly understand what make you say that it may in some way be related to the database. May you explain what take you to this affirmation ? Only assets go into the cache, not the results of fetches from the database. So for the database to be the cause of messed up menus **_or_** display then it would mean that the query aren't created or processed properly. As we use prepared statement then I don't know how could this be possible.

**Comment by pH-7** [comment] 2019-03-05 07:18
Maybe an issue with your URL somehow... 

Can you try to remove these lines? https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/static/js/common.js#L61-L83

From line 61 to 83 in `static/js/common.js`, save it, clear your web browser's cache (and the [Static Files Cache in Admin Panel](https://ph7cms.com/doc/en/how-to-clear-caches) if you use another template than the default "base" one).

**Closed** 2019-03-29 08:38 UTC
Labels: archived
