### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by jules8791** [pH7Software/pH7-Social-Dating-CMS#156] opened 2017-12-19 19:12 UTC
Hi,

I have tried installing PH7 and once the installation has finished the admin123 folder isn't created so I am unable to administrate the site. Any ideas for this?

Thanks

**Comment by pH-7** [comment] 2017-12-19 20:02
The `admin123` URL is always there (it is made with `mod_rewrite` apache). 
Please try to go to your-website.com/admin123

**Have a look here https://ph7cms.com/doc/en/how-to-go-to-admin-panel**

**Comment by pH-7** [comment] 2017-12-19 20:04
Please make sure the URL rewriter is made properly from your web server.

Please let me know as soon as you can.

THanks @jules8791 

Good luck 😃

**Comment by pH-7** [comment] 2017-12-19 20:04
Finally, please STAR the repo in order to get the latest updates.

**Comment by jules8791** [comment] 2017-12-19 20:13
Hi
The admin123 folder isn't in the html folder either I cloned the repo today, I have tried the hostname and the ip address no joy

**Comment by pH-7** [comment] 2017-12-19 21:23
No, that's normal. The router knows when to show the admin panel when you type (www.mysite.com/admin123/).

What's your website URL?

**Comment by pH-7** [comment] 2018-01-07 12:33
Since I didn't hear from you. I suppose the problem is now fixed. Thanks

**Closed by pH-7** 2018-01-07 12:33 UTC
