### ISSUE TITLE
ph7 in android

### ISSUE THREAD

**Issue by saman-magnus** [pH7Software/pH7-Social-Dating-CMS#247] opened 2018-07-20 03:58 UTC
i try this progy ist perfect, congratulations...
but i find a bug so i reported .
in android (navigation bar) click on (search) is not Stable , for example,,, if u click on search must be show u { Quick search} & {Advance search} but in android this not working exactly ,
Thanks.....

**Comment by polynamaude** [comment] 2018-07-20 10:05
@saman-magnus The application use the browser integrated into Android. We simply make application that call the browser but add option to the URL indicating that it should be optimized for mobile.

PM

**Comment by pH-7** [comment] 2018-07-20 13:47
Hi @saman-magnus 

Thanks for your feedback! I couldn't replicate it. Can you send a screenshot showing the issue?

Thanks

**Comment by polynamaude** [comment] 2018-07-20 14:51
@saman-magnus Hi,
Have you compiled your .apk from the sources or used a prebuilt application ?

**Comment by polynamaude** [comment] 2018-07-20 14:57
@pH-7 We seem to be getting lot more reports from users who create a gitHub account for the sole reason of opening a issue.

We could deduce it as a proof that it's touching a wider visibility.

PM

**Comment by polynamaude** [comment] 2018-07-20 15:03
@pH-7 I checked out his installation on https://azyek.com/ using both plain the Android browser and the Lightning browser. Everything looked fine to me.

@saman-magnus Have tried to create a Persian translation using right to left text language?

**Comment by saman-magnus** [comment] 2018-07-20 23:31
hi guys, i uploaded test video in https://youtu.be/tfSZmY-47Lg so u can see whats exactly problem ,i try it in google chrome miniopera and android webbrowser.
last night i try to fix this from css class but nothing :) 
so thank u for answering & following...

**Comment by pH-7** [comment] 2018-07-21 18:09
Thanks @saman-magnus!
This looks like to be on a tablet, so you get a desktop menu.
Can you try to drag your finger from People to "Search" and keep it on Search, then you should see the sub drop-down menu appearing (without clicking on the links). The menus appears when you keep your finger on it, not when you are clicking on it (like when you are navigating on the menu with desktops; It's the same thing).

Thanks for the clear video! I really appreciate it :)

**Comment by pH-7** [comment] 2018-07-21 18:12
Thanks @saman-magnus!
This looks like to be on a tablet, so you get a desktop resolution menu.
Can you try to slide your finger across the menus, from People to "Search" and keep it on Search, then you should see the sub drop-down menu appearing (without clicking on the links). The menus appears when you keep your finger on it, not when you are clicking on it (like when you are navigating on the menu with desktops; It's the same thing).

Thanks for the clear video! I really appreciate it :)

**Comment by pH-7** [comment] 2018-07-25 09:52
Hi again @saman-magnus 
Hopefully this helps. Let me know if your issue is still relevant?

Thanks

**Comment by pH-7** [comment] 2018-07-29 19:22
@saman-magnus Since you didn't get back to me, I'm closing it. Please reopen if the issue is still relevant for you. Thanks

**Closed by pH-7** 2018-07-29 19:22 UTC
