### ISSUE TITLE
Regular User 

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#545] opened 2019-05-12 00:27 UTC
1) I created a test profile so i can check my changes & edits. So by default I am a regular user/membership. When i log in, immediately the upgrade membership Payment Zone page comes up. 

![image](https://user-images.githubusercontent.com/50240615/57576292-3b121500-742a-11e9-97d0-ce8f30bbedb8.png)

I have the regular user membership set to expire in 45 days. Is this not correct?  

I need regular members to be able to access the site, look around for 45 days before being immediately prompted to subscribe so... how do i disable that payment zone page from being the very first page they see when they log in?

2) The Payment Zone page has on it "subscription", how do i change that to "membership"?

Thanks.

**Comment by polynamaude** [comment] 2019-05-12 00:39
@CooperAshley2 Like I already mentionned on another post (https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/535). You can search through the whole source code by using the **_fgrep_** command. Look for the word _subscription_ and replace it by _membership_ in the template files found.

You shoud try to do some research on your own before asking out questions. We are all volunteer and have precious spare time. It's nice to see interest in our CMS software but we can't just take people by the hand to build their own web site.

The CMS is based on the MVC architectures with a easy to follow source tree. All the modules have a folder with the templates. Look into **__protected/app/system/modules/payment/views/base/tpl/main_** and you'll find what you looked for.

PM

**Comment by CooperAshley2** [comment] 2019-05-12 01:18
Thanks PM, you're the best! I made the changes (deleted/added wording) to my tpl pages, cleared the caches and still the verbage didn't change on the page in my browser. Is there another page I need to change as well?

Still, I have the regular membership issue. How do i stop that Payment Zone page from even appearing? Is the expiration days of 45 not correct?

Thanks again, enjoy your day (or evening).

**Comment by polynamaude** [comment] 2019-05-12 01:52
@CooperAshley2 First, as already said (many time). Ask one question, wait for the answer. Don't ask ten questions in a single issue. The title of the issue becomes useless in such case and it makes it very hard for other people to use such as references.

I've written a small text on hints if you want to get help.
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

First of all, try accessing your site from a browser with a private (incognito on Chrome) window. Even if you clear the cache on your server it doesn't help with your browser caching content.

Concerning your problem with membership issue, I'll have to take a deeper look into. But at first maybe you should yourself build some knowledge about operating a web server (much more than simply PHP programming).

**Comment by Nigrini** [comment] 2019-05-12 07:17
@CooperAshley2

Regarding your membership issue. Log into your admin section, Go to Settings -> General ->registration.

Rigth at the bottom you will see default Membership Group. I think at the moment it is Visitor(not visible) in your case. Change that to Regular(Free)

**Comment by CooperAshley2** [comment] 2019-05-12 20:33
@Nigrini, Thanks for your response. I actually have that set to Regular(Free). 
Last week while scrolling through the questions and issues from other users, someone asked the same question, which Mr. PH7 responded to but of course I can't find it now when i need it.

**Comment by Nigrini** [comment] 2019-05-13 05:55
@CooperAshley2

Since installing the latest version of the script I am facing some small issues as well, and I just notice that I am having the same issue as you. When I change mine to one of the other plans it does not save it, and is falling back on Visitor(not visible) status.

**Comment by CooperAshley2** [comment] 2019-05-17 00:46
Mr. de Soria, any assistance with out issue will be greatly appreciated. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by polynamaude** [comment] 2019-05-17 05:46
@CooperAshley2 Hi !
I'd start by asking you to read the following issue https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/549

Afterward, I'll add a simple thing. If you find a bug and give us enough information that we can reproduce it then we'll do our best to fix it.

Other than that, you're in the possibility. I mean, maybe if there's free time and someone feel like it. But if I look at what you asked (many time) then maybe you'd be better off search for a freelance developer (as we have already told you).

Also, how do you expect us to know that there's a possible bug (issue) if you don't report it ??
Maybe you ignore the fact that when you open an issue, we can make code modification and link it to this particular issue, so it gets closed when the problem is solved.

Example
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/543

https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/6914c56f828856b20c5065cd869269f8a45a6f41

Hope you start to get the point here.

**Comment by Nigrini** [comment] 2019-05-17 06:26
@ CooperAshley2 

What is your current version you are running. If it is the final 15.1 release I would suggest you download the 15.1 SR2 zip file, and extract it somewhere on your drive.

Now Delete the following from the newly extracted zip file 
- _protected/framework/Security/Version.class.php
- The _install/ folder.

Now upload ALL the files and folders to your hosting environment

Now login to the admin panel.
Go ->Mod ->Billing ->Memberships List
Edit the default group (The default group will be the one you have specified in General settings -> Registration)
Depending on what you pick the default member will be able to use a function or not. If you disallow a certain function the user will get the update your membership plan when he try to use the function.

Hope this helps. If you want/willing I can do a team viewer session to you and try to help you that way

**Comment by polynamaude** [comment] 2019-05-17 19:35
@Nigrini By pushing the files from one version over the other and keeping the same **_protected/framework/Security/Version.class.php** (only not to get bothered by the _upgrade_ message) you risk causing more problem than anything else on the long run.

Don't ask for help if you don't want to make the effort of following what we suggest you. In my message, I've asked you if you simply pushed over all the archive files or some specific ones. You never answered but I saw here what you did.

Instead of going back to a passed version why don't you look at the changes made and try to find where the problem may come from ? It ain't too hard, just follow the folders and you'll find the file used to build the form. After you look at the differences between the files (diff). It's all quite simple when you want to do things right.

Unless you're on a manic style action thinking that you'll build an online dating site without planing or investing time (the "I got an idea and make a fortune out of it" but not thinking that we're 5 billions and more on this planet, so you're not the first one thinking about this).

**Comment by CooperAshley2** [comment] 2019-05-17 21:18
Yeah, I’m all set with this piece of shit “dating” script. If anyone can even call it that!! I’m also all set with you, Mr. Holy-er Than God, my shit dont stink Poly M whatever the fuck your name is. Instead of speaking down to everyone who asks a question about this fucked up script... if you dont want to answer our questions then simply don’t! Get your sorry ass off of your high horse and go fuck yourself! Go get laid for crissakes!

Ive yet to see any successful dating site anywhere that uses this script. And you want us to support and donate money for your time? For what!?! A fucked up script that doesn’t work? Oh please, again, go fuck yourself and the horse you rode in on. I’m done with your bullshit!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by polynamaude** [comment] 2019-05-18 04:53
@CooperAshley2 Thanks for the sweet advice. You must be a bit confused because last week you we're saying that I'm the best. But you are right twice in a row. I should have let pass more time before explaining that maybe you are on the wrong project if you expect everything to work Out-of-the-box.

I do understand your frustration that you can't do everything by "clicking around" and that you'll have to learn what does

**Comment by polynamaude** [comment] 2019-05-18 05:19
@CooperAshley2 Just a little thing about life. We call other peoples work shit only when we can do better. And here it's far from your case.

https://www.php.net/manual/en/language.basic-syntax.comments.php

**Comment by Nigrini** [comment] 2019-05-18 08:28
@polynamaude

1. I told you that I did not keep a record of the individual files that I replaced.
2. I told you that I han a "Test Lab" environment as well.
3. CooperAshley does NOT seems to be an IT person

Therefore the advice I gave him was to get reid of his problem without having to go to individual files and or modules, and it work quite well as I have tested it out for myself.

And I will say it again - Tone down your (aggression level / school teacher mode), answers to the people asking questions. It is getting tiresome

**Comment by polynamaude** [comment] 2019-05-18 16:29
@Nigrini In life, you have no guarantee whatsoever.
I have much better to do (a.k.a. real stuff like making plenty of cash) than to repeat myself over again.
When someone explain something there's two possibility, either you take it as "I can learn something but it may require me to change some of my action" and the other way "You just get angry that we are explaining it to you".

I'm not talking about a nuisance list, I'm talking about the good place for some questions.
Go read on Stackoverflow and you'll get the point.
Go ask on the Linux kernel mailing list a question about using a C++ compiler or how to code.
Go on the Apache Web server mailing list and ask a question about the specificity of the HTTP 1.1 protocol.

When either me or Pierre-Henry tell someone that maybe they should hire a developer, I think that's some hint that this person is lacking some technical skills.

If you read back the threads I answered you'll see that I'm always answering all the questions and even the ones that aren't related but I do tell the person that she's not at the good place for such question.

Concerning the numbers if issue, what I did say was that this person opened a number of issue, in a pretty short amount of time and that's some sign she may be needing help. I didn't say it was too much, not at all. I even said in one of my post that if she found that problem she shall open an issue, not write a message in a thread. And I did take the time to explain why, linking **commits** and issue, closing them when the code is written and bug fixed.

I don't have any of the problems you see with anyone who follow basic rules in developer community. And we mostly see it by the time and investment they did in other project, not only opening a Github account because they need help with pH7CMS (and think they'll be the next Ashley Maddison without coding a line).

What I say here, you may not want to read it, but it's mainly all true.

If you want guarantees then I'll redirect you to UNA ( https://www.una.io ) at 50 and 100 dollars per month, you are going to get served.

In life there's a thing called faith, so if you need a guarantee when you give 20$ then my answer is pretty simple. What you already have is worth more than 20$.

If it doesn't fit in your mind that the only thing I try here, is to make people understand that time is limited and if they ask many **_easy question that they can find their answer somewhere else_** then in the long run we won't have the time to answer real question, related to this software. If you prefer let me explain something (Like a school teacher). If a friend of yours ask you "How do I make a cake", you send her a recipe, she come back and ask "What's flour". At first you are going to answer her "You can buy flour at the grocery store, etc". Now she ask you "What's a spoon ?".

There's two possibility...
You explain to her everything about life (even if you have limited time and resources) and one day she discover that she doesn't know how to find her own answer, having a big problem because you can't answer the phone so she doesn't have her solution.

You explain to her that she can ask you question that need development and specific help (For example, can I add chocolate chips to the cake mix) but for question like "What's flour ?" then she can certainly find the answer by herself.

A good technician / developer does not know everything in his mind. Not at all, he's (or in my case she is) good at making research to find answers, to learn and to evaluate the quality of information.

I don't understand what you say here
_People take the base initially and log issues, but because of the replies they get, decides to do development themselves, or hire someone._

Great if people can be autonomous, if they report the bug they find in a useful way then it's even better. And if they need to hire a developer then it's their own business and it's also quite normal too. What you are saying here is non-sense, it's not because you buy a word processor that you're a prolific writer and it's not because you buy a hammer that it makes you a carpenter (even if you did work around your house). It's a place to post issue relating to pH7CMS, not a place to learn programming or how to do web design.

Go on some developer mailing for some nice big project, you'll see quite fast two things. First when the question are unrelated or part of the documentation, you get **warning**, **suspension** and finally **banned**. And if you think I'm rude then maybe you don't get the english language very well.

You may not like my answer but everyone who asked question, did get a good answer with a solution, nearly all the time. So on my part, it's closed and will remain.

And on a last note, when you make a donation, you make a donation. It's not because you want something in return. It's because you want to say thank you. That's all.

When you give your kids, your wife (or husband), your parents a gift. Do you ask for something in return ? Not at all.

If it's rude to remind people of their own limit and that they their project won't work on the long run with the technical skills they got, then yes I'm rude. But one day, they'll look back in time and understand that I was right.

Unless you can tell me how can someone operate a website, without external help, if they don't have the knowledge to modify the user interface, etc ?

You ever tried using XDebug ?

**Comment by polynamaude** [comment] 2019-05-18 16:32
@Nigrini Again, they type of complains (about not liking when I say the question are unrelated or that people need to hire someone) only come from Github (Developer community) users who opened their account for filing issues with pH7CMS.

Other people who have large contribution to many repository understand quite good.

A couple of years ago I gave a book "For dummies" concerning Internet to my nephew. In one of the chapter the author was saying "To ask question relevant to the domain on the mailing list" and to read documentation before asking question because of the risk of being "RTFM". He must be a very rude school teacher.

**Comment by Nigrini** [comment] 2019-05-18 17:20
@polynamaude

You know what - You are right, you go on answering the issues the way you want to. 

Personally I am in the position to evaluate the current status quo and decide to move on to UNA or something else if needed, keeping in mind the pathetic Rand vs Dollar exchange rate. The whole dating site thing is more out of curiosity for me, hence my unwillingness to pay / contribute unless I am sure that I have a product that will eventually earn it's existence. I am after all FIRST a business man, not a developer. 

I am "happy" with the current setup that I have. But to be honest I will not go live with it. I truly wanted to contribute and make the software into a "complete" product, but is it clear to me now that I was wrong.

If and when this whole Ph7Builder project turns to shit, please have the honesty and acknowledge your part in it.

This will be my last post regarding this software - I cannot see this as a viable option to proceed with

**Comment by polynamaude** [comment] 2019-05-18 17:35
@Nigrini Whatever product you'll choose, either you'll have to pay for licensing fee or pay to modify it to suits your needs. In most case, you'll pay for both.

You should have enough respect to see the work of others and it's clearly not the case. What you call "shit" is many man-hours of work, thousands of them. Write Pierre-Henry a email and ask him why he doesn't offer to do custom development on a monetary basis anymore. The answer is quite interesting.

I won't take a part in what you call "acknowledge my part in it" because the ones who ain't happy are those same person who aren't serious in their work. Start by learning the basis of web development before trying to run a site. That's f*cking plain simple.

And for god sake, don't compare project run by a handful (or less) of person versus project backed by millions of dollars worth company.

If you're a business man then make a plan.

And at last, learn to give and you'll get a feeling of reward one day.

Unless your only hope is to die alone with all your "rands"

**Comment by polynamaude** [comment] 2019-05-19 01:15
@Nigrini If you'd have asked me a way to keep track of the changes you make to source code and even revert back when needed then you would have gotten an answer. You would have learned that all this is done using _git_. When I see that someone is willing to contribute and not only take benefit then I'm there to give a helping hand.

You said you wanted to help with documentation. Great ! But you changed your mind when you saw the real effort involved. It's like if you expected the Symfony framework to build a website for you, without coding.

You wanted so much to blame someone else for your own cupidity that you never looked at any references I gave you or even consider them.

**Comment by Nigrini** [comment] 2019-05-20 06:38
Please don't cherry pick through my posts.

1. I have a lot of respect for Pierre-Henry and will continue to help HIM.
2. But I will do so by emailing him directly
3. Ironic that point 3 is also the amount of people that have an issue with your attitude and way of answering. And because of that 2 of them opted to rather leave the software completely. 
4. 3-2=1 Two people less to help with testing and finding bugs, so yes you will have to take the credit for that.

**Comment by polynamaude** [comment] 2019-05-20 06:59
@Nigrini You seem well messed up in your words. You say you don't think this software is worth using but you will continue to help out. Quite strange way of thinking.  I don't cherrypick your post.

Happy to read you will still be helping to find bugs. Like the last one you found. Great jobs for the membership levels.

Use git to record your changes by first making a fork. You will be able to push back with a Pull Request.

**Comment by polynamaude** [comment] 2019-05-20 07:01
@Nigrini To help out doesn't start by asking for help.

**Comment by polynamaude** [comment] 2019-05-20 07:14
@Nigrini Go see your issue #516 that's as much help you can be.

**Closed** 2019-06-13 09:03 UTC
Labels: archived
