### ISSUE TITLE
Getting pH7CMS to work on Plesk system

### ISSUE THREAD

**Issue by burtonio1985** [pH7Software/pH7-Social-Dating-CMS#193] opened 2018-03-31 18:01 UTC
I can't for the life of me get pH7CMS to work. I've uploaded all the files, setup the database. Ran through the installation and to the point where I have to delete the install file. As soon as the install file is deleted the site brings up a is 'currently unable to handle this request.
HTTP ERROR 500'

I believe the server is running nginx with apache.  I can't seem to get a clear idea of whats required from the nginx configuration page or at least anything I've implemented doesn't work. I can provide access to the hosting to somebody who would be willing to take a look and see whats missing.

Any tips or ideas would be appreciated, I've reset the install so at the moment just the basic files are present and I haven't made any changes pending some advice.

Thank you in advance.

Chris

**Comment by polynamaude** [comment] 2018-03-31 22:00
Hi !
At first it will be needed to get some more information about your situation. As you probably know, the more we know about your problem and your system, the better your chance that we'll be able to help you.

When you get a 500 Error ( HTTP Answer Code of 500 ) it means that the software can't process your request. It doesn't say much and can be caused by many situations including error in your htacess file, php code that doesn't work properly, modules that crashed and much more.

Look into your logs and you'll find a detailed description of the problem.

I copied a small piece of a log file so you can see where to information may be found

error-tiki18.log.1:2:[Sat Mar 10 22:26:30.044069 2018] **[rewrite:error]** [pid 32167] [client 127.0.0.1:60952] AH00670: **_Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions_** : /var/www/tiki18/tiki-index.php

This error would give back a Error 500 type to the user but inside the logs you get what really caused the problem.

For example if you make a typo and insert a "_**Dany** from all_" instead of a "_**Deny** from all_" you'll get a 500 too. As if you have the PHP module that's misconfigured and not loading properly. I'm not saying that's your case but explaining to you that with what you gave us there's not much we can do to help out.

You say:
_I believe the server is running **nginx** with **apache**. I can't seem to get a clear idea of whats required from the nginx configuration page or at least anything I've implemented doesn't work. I can provide access to the hosting to somebody who would be willing to take a look and see whats missing._

You're either running a instance of Apache or a instance of Nginx, possibly both on the same server running for different port or virtual hosts but not for the same one. It's either you're serving the application with Apache or Nginx. Take a look at your configurations and get us back on that. I'm not too used with Nginix but I can sure try to give you some help with it.

I would make the first recommendation and it would be to do the installation without the use of a software installer like Softaculous or such. Did you install the software by unpacking into a folder and then browsing into the installation ?

Have you tried at first to do the installation over your own computer (for example using Wamp or Bitnami) ?

Get us back and we'll sure get this beast running like a horse

**Comment by polynamaude** [comment] 2018-03-31 22:03
Hi !
At first it will be needed to get some more information about your situation. As you probably know, the more we know about your problem and your system, the better your chance that we'll be able to help you.

When you get a 500 Error ( HTTP Answer Code of 500 ) it means that the software can't process your request. It doesn't say much and can be caused by many situations including error in your htacess file, php code that doesn't work properly, modules that crashed and much more.

Look into your logs and you'll find a detailed description of the problem.

I copied a small piece of a log file so you can see where to information may be found

error-tiki18.log.1:2:[Sat Mar 10 22:26:30.044069 2018] **[rewrite:error]** [pid 32167] [client 127.0.0.1:60952] AH00670: **_Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions_** : /var/www/tiki18/tiki-index.php

This error would give back a Error 500 type to the user but inside the logs you get what really caused the problem.

For example if you make a typo and insert a "_**Dany** from all_" instead of a "_**Deny** from all_" you'll get a 500 too. As if you have the PHP module that's misconfigured and not loading properly. I'm not saying that's your case but explaining to you that with what you gave us there's not much we can do to help out.

You say:
_I believe the server is running **nginx** with **apache**. I can't seem to get a clear idea of whats required from the nginx configuration page or at least anything I've implemented doesn't work. I can provide access to the hosting to somebody who would be willing to take a look and see whats missing._

You're either running a instance of Apache or a instance of Nginx, possibly both on the same server running for different port or virtual hosts but not for the same one. It's either you're serving the application with Apache or Nginx. Take a look at your configurations and get us back on that. I'm not too used with Nginix but I can sure try to give you some help with it.

I would make the first recommendation and it would be to do the installation without the use of a software installer like Softaculous or such. Did you install the software by unpacking into a folder and then browsing into the installation ?

Have you tried at first to do the installation over your own computer (for example using Wamp or Bitnami) ?

Get us back and we'll sure get this beast running like a horse

**Comment by burtonio1985** [comment] 2018-04-01 11:58
Hi thanks for getting back to me. I found the following error in the logs-

[Sat Mar 31 10:08:30 2018] [error] [client 92.239.0.206] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

I've checked and 'Fastcgi' is processing the php script.

I was initially installing the files using ftpzilla. But when the problem occurred  I thought it might of been because of a file missing off the upload. So I started uploading using the file manager in my hosting package. I uploaded the zip file and extracted it.

Your help is appreciated.

P.s- I've emailed you login details to the hosting panel so you can take a closer look.
Thank you so much.
Chris

**Comment by polynamaude** [comment] 2018-04-01 13:30
Hi there !
I think we've got a little misunderstanding here... you're not getting a paid technical support or some other form of contractual service. It's a volunteer support forum or user help group, call it as you want.

I'll give you some advice but I won't be doing the job for you. What you are asking me here is both _insulting_ (**as you send me the information and expect that I'll do it, you don't even take the time to ask me and wait until I give answer back**) and quite _stupid_ (**as you will never know what to do if such problem occurs again as you won't be fixing it**).

Oh, I'm pretty sure you may find offending to get such answer but on the long run you'll be thanking me as you'll be understanding where does the problem get it's root and how to do diagnostics.

By the way, it's way more painful than to simply use your credentials and do the job for you.

Like the log information does suggest you, I would increase the "LogLevel" to get more information and try another connect so you'll get more information about where it starts. Have you done that yet ? Or you're simply playing the Jewish and hoping for god to come down to you ?

Do you use the actual .htaccess or have you modified it in some way ?

I will be giving you a small  .htaccess file so you can try with this one.

Just rename it to .htaccess in the root folder of you webserver serving directory (public_html) probably.

[small-ph7cms.htaccess.txt](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/1866375/small-ph7cms.htaccess.txt)

It does make the assumption that you've got mod_rewrite and others modules properly installed so it's a good test to see if the basic needed stuff is working.

Could it be that you unquoted both Rewriting to index.php AND init.ph7 ?

Try those step and get me back with the results. After you'll have done your share of the work and effort, maybe then will it be wise for me to take a look.

Sincerely,
PM

**Comment by burtonio1985** [comment] 2018-04-01 14:05
Hi thanks for getting back to me. 

I was in no way trying to insult you or be stupid about this, I simply wanted to be transparent with information. Your help is much appreciated so I'm sorry if I was alittle presumptuous. 

I was using the original .htaccess file and have now uploaded yours.

I wasn't playing the jewish, I simply don't know how to increase the error log, I'll start researching this now to see how to do this. There is an error log on the hosting panel which generated this:

2018-04-01 14:49:32 | Error | 92.239.0.206 | 500 | GET / HTTP/1.1 |   |   | 415 | Apache access
Which seems pretty undescriptive.

I looked into mod_rewrite with host and got this-

How do I enable mod_rewrite?
The mod_rewrite module is enabled by default in Apache that comes with Plesk for Linux. To make use of the functionality, you will need to create an .htaccess file containing the desired rewrite rules.
So that looks fine.

I haven't unquoted both Rewriting.

I work on trying to increase "Loglevel" and update shortly.

Thanks again.
Chris

**Comment by polynamaude** [comment] 2018-04-01 14:13
Check in the Apache documentation and you'll get all the information you need about make configuration changes.

The error you've getting (415 - Media type not supported) is a problem with your server configuration and not pH7CMS. I'll suggest you contact your hosting provider about this type of problem at first.

It sound much like a problem involving Apache configuration support than something related to the CMS.

Happy easter !

**Comment by polynamaude** [comment] 2018-04-01 17:11
It may be the best option for now as they'll be able to help you with augmenting the LogLevel. You can also check with the Apache Documentation if you can effectively augment the LogLevel in a directory configuration file (.htaccess). I'm not too sure this is possible as it may leak out some security information from the hosting provider and some will limit such.

What you are simply get in your first case (the redirection errors) seem to be related to redirection that goes back onto itself. It was solved when I send you the basic .htaccess file and you used it. But now what you are getting is a bit more complex and related to the server internal.

After you contacted them, ask for complete answer. Don't accept stuff such as "your .htaccess file is not compatible with the last Apache version", ask why and to get a proof of what the person is saying. Simply said, what made her come to that conclusion. Too often technical support of some hosting provider will just be making assumption and stop there. But when you go with good one, then you may get real nice help. The main reason why I suggested you look into them is that the error changed with the change of file and also because they actually get used to this kind of problem that occurs specially because of the own configuration and not because of the way we operate the software. So as they get this kind of problem often, they already have mostly the solution.

The pH7CMS is highly optimized and as such, use the software to it's maximum possibility to get most out of the less resources possible. It allows you to run as much connexion as possible without getting a huge server load. But as such it does make some bugs go wild or misconfiguration should I say, to be precise, I'd say that it show some limits that hosting provider impose but don't disclose in what can be done with they're service.

In this actual case I believe it can be related to either the caching system that use a "curl" command to go fetch the files on the server and it may cause some problem with files being served (why you get the media error 415). It can also be related to they're own security rules (and that we don't know about).

Get me back with they're answer and we'll get that beast on track.

It's always nice to help people out as it gives me (us) better knowledge and also we can add the solution into our minds if we get something alike with this or other software.

I think it's not really related to the caching system or the way we use a fetch to get files cached as you don't even get anything and in case of caching problem, at least you get some text.

I wouldn't want to get onto your system and change something on your other services running if I do some try to fix it. So tell me do you have other instances running on the same account ? Do you have some kind of shell access ?

Thanks for your cooperation, I didn't want to be rude or such but I like to make it clear as too often people think that everything can be done in a "point-click-play" and expect not to be needing some text file editing or programming. But that is needed if you want to get anything as customisation and it's not only for this CMS but most of the other ones too. For sure you can get along without doing programming by using Joomla with standard templates and simply configuring many modules but your site will be much like many other and you'll end up wasting money for stuff that can be easily programmed.

If you want some references for books on either PHP, Apache Hosting or such, just tell me and I'll send you some good free stuff.

PM

**Closed** 2018-04-21 12:29 UTC
