### ISSUE TITLE
Warning, these permissions don't allow editing and creating files in the File Management admin module.

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#444] opened 2019-02-19 06:05 UTC
I already give the 777 permissions to 10 folders that installation manual suggested but then I came up with these two lines and didn't understand what exactly it means:
Warning, these permissions don't allow editing and creating files in the **File Management admin module**.
If you want to allow it, you need to set in numerical values **777 for all folders and 666 for all files**.

**Comment by polynamaude** [comment] 2019-02-19 06:09
I'm pretty sure it means exactly what it says !
If you set the permission as stated then you won't be able to create and edit file using the "File Management" admin module.

Give you a hint ;-)
You ain't doing a life support system so try out different possibility and you'll understand better.

**Comment by polynamaude** [comment] 2019-02-19 06:11
As we are all volunteer, it would be appreciated if you could "star" our repository.
<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/52993701-1f770f80-33e3-11e9-913a-b32372c10503.png">

And please close your issue as you already opened one for quite the same thing.
Help is non unlimited so use wisely.

We ain't here to give programming courses. I doubt that there's a real problem behind this type of question.

**Comment by polynamaude** [comment] 2019-02-19 06:12
Duplicate of #441

**Comment by kevinbkk** [comment] 2019-02-19 06:40
Ah I see, just to make sure that I get you right, what you mean is I can skip it if I don't want to use the module that could be find in this URL:
https://freetraveldating.com/admin123/file/display#elf_l1_Lw

**Comment by pH-7** [comment] 2019-02-19 06:55
Thank you @polynamaude for your help! Indeed, this is a duplicated one. 

@kevinbkk Please keep updating #441 if you have any further issus. I would suggest to see with your web hosting company if you have problem with the permissions in there. Thanks & Good luck!

**Closed by pH-7** 2019-02-19 06:55 UTC
