### ISSUE TITLE
How to rename the "admin123" folder

### ISSUE THREAD

**Issue by sewcherry** [pH7Software/pH7-Social-Dating-CMS#771] opened 2020-05-09 20:54 UTC
I followed the directions at https://ph7cms.com/doc/en/rename-the-admin-folder about renaming the admin folder. Changed the constants.php file and removed the uri cache folder and it still doesn't work at the new folder I specified. I can still go to the original admin123 location and it works.

I'm on version 15.4. Any ideas? Thanks!

Kelley

**Comment by polynamaude** [comment] 2020-05-09 22:07
@sewcherry 
Hi !
Have you renamed the folder itself on your server ?

Doesn't start very good...

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by sewcherry** [comment] 2020-05-09 22:58
There are no folders with that name. I followed the instructions on how to rename the folder. It doesn't work. There are 3 modules names admin123 and a compiled cache starting with admin123. Either way, there is nothing that mentions changing a folder name.

**Comment by polynamaude** [comment] 2020-05-09 23:21
@sewcherry Liste cherry poppin...

Here's what the page says, if it ain't clear enough for you then maybe you don't have the needed background to run a web service.

**To do this, rename the folder with the name of your choice, then edit the file ~/YOUR_PROTECTED_FOLDER/app/configs/constants.php and change**

[admin123](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/system/modules)

Maybe you shall try to learn the difference between a issue (something wrong with a system) and a lack of knowledge (I'm trying to use carpenter tool but I'm a freelance taxi driver).

**Comment by sewcherry** [comment] 2020-05-10 00:55
I'm sorry you feel the need to be rude. I did not read the instructions as the folder in the MODULES should be changed. Maybe that should be made clearer. And for the record, I have been a programmer/developer for over 20 years, I'm just not a familiar with PHP. Thanks for the help though.

**Comment by polynamaude** [comment] 2020-05-10 03:05
@sewcherry Just a simple thing... most up-to-date programmer have active Github account not only created to open an issue regarding how to operated a website in a language they don't master...

Sound like someone complaining about compiling error with G++ but don't know much about how to write in C itself.
Maybe learning a language before trying to run a website can be a good start. Also, it means quite nothing the word being a programmer/developer. It's not because you've been doing something for the last 20 years that you're up to date or that you've been doing it well.
My grand mother used to put baking soda in her sauces saying it would lower the acidity and make it easier on her stomach. Maybe it did lower the acidity in her dishes but the cause of her stomach pain was the hydrochloric acid produced by the body itself. It's not because you do something for a while that you do it good and it's not because you do something without understanding that it's well done.

At least, as some basic manners for someone so much experienced, you could close the issue unless you think your problem hasn't been solved ?

**Comment by sewcherry** [comment] 2020-05-10 16:01
Just because i haven't contributed doesn't mean i just opened this account. I was primarily a PERL and Cold Fusion programmer. So yeah, i know how to run a website. But yes, thank you again for your condescending attitude. I remember why i don't contribute to anything.

**Comment by sewcherry** [comment] 2020-05-10 16:04
And if you believe that this is a better item for a help section than issues, maybe you could point me in that direction instead.

**Comment by polynamaude** [comment] 2020-05-10 18:09
@sewcherry Don't confuse issue with a software with offering customer support.
I don't know what type of english you speak but when we write "Rename the folder to the name of your choice", it's hard to be more clear than this.

Oh, I see that your account was created in 2013 maybe but still, it would be good you'd stop to take and give a bit...

Just like that, PERL and ColdFusion are mostly outdated and not very used anymore except in specific use case.

**Comment by sewcherry** [comment] 2020-05-10 21:28
I agree with the shared issue not being a customer support issue. I saw someone else in the

**Comment by sewcherry** [comment] 2020-05-10 21:35
I don't disagree software and support issues are different, like i said if there's another place or maybe community support, i would love to know where that is. I did search using Google as well as this repository and there was another question similar to this one, and that person received help.

I am a native English speaker from the US, so yes it makes sense, but it could have been clearer. Did i need to rename all of the admin123 folders? Where are they located? This information would have made it more clear. I'm not stupid and am used to figuring stuff out, but thought i would ask for help when it wasn't working as expected even after I thought I followed the directions.

I was a developer, but i also work in UX and have written user guides and manuals, and the directions could have been clearer and/or more precise.

I am a giver. Maybe not on GitHub but i gladly and freely share my knowledge. So again, if there a community support group or other place i should go for this type of support?

**Comment by polynamaude** [comment] 2020-05-10 22:23
@sewcherry Great if you feel like writing ! Then write us a nice guide... and I'll publish it.

I made many corrections on the pages here and will be a pleasure to add your user guide. But maybe you shall notice a difference as this software ain't meant for end-user. It's meant for developers who have time to invest, at first customizing it to their own need and possibly doing some troubleshooting for installation. As we don't have a big user base, it's hard for us to test all the possible different installation scenarios.

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

Now regarding support, how can I say... It's not because something doesn't exist in the form that you'd expect that it make it okay to go the wrong place. If you need help learning or supporting your installation then you can hire a developer on UpWork or something similar.

Yes we do support people, when they find bugs in the software itself.
If you want real support then maybe you'd be better looking at [Una](https://www.una.io)
You'll get what you want for your bucks.

You ask for support like if it was something due to you or something that for sure is available. No ones getting paid here and it's all volunteer.

The software was mostly written as a one-man project by PH and now I'm helping him with one or two other users. Don't expect much as our resources are pretty scarce. Don't think the same service level as Joomla/Elgg or whatever else. It's closer to a framework than a complete dating site. You'll have customization to do and programming too if you want to get something really useful working. But at least, you'll get a well written base with good documentation in the code.

**Closed by polynamaude** 2020-05-10 22:23 UTC

**Comment by sewcherry** [comment] 2020-05-11 01:13
Thank you for the links. I really do appreciate it. I actually chose this software because of its features and extremely clean code. I do really appreciate that. I was asking for help with what i thought was a simple question and apparently i just shouldn't have. Again, thank you.

**Comment by polynamaude** [comment] 2020-05-11 02:15
@sewcherry It's not a thing about asking for help or not.
It's about knowing what you are diving into.
Some people come here and expect that we'll support them all the way with the step of putting up their website. They hope to have answers with every thing and that we'll explain stuff from HTML tags to how to build a mobule and what's AJAX.

I always had the belief that the explaination are simple regarding how to rename the admin access.

Yes the code is pretty clean and easy to understand but there's much work to get done too.

There's also some nice extensions pack for Joomla (JoomSocial) if you feel like taking a look at this. Maybe it can be a better start. There's also the Dolphin Pro software that's the base used for Una.

**Comment by Undefined-Variables** [comment] 2020-05-12 03:09
@sewcherry If you have the free time to write documentation knock yourself out! I wish I had the time to do more! 

@polynamaude What is AJAX haha that put a smile on my face! Website's were long winded before this incredible idea! I remember the blue bar that took 5minutes to load a single page! 

@pH-7 Do you think running a forum specifically for the software would be beneficial to the software? Happy to host one if you think so. Its just this is about the 12th person who I've seen ask for it! Let me know!

**Comment by polynamaude** [comment] 2020-05-12 03:38
@Undefined-Variables Hi !
How y'a doing bro ? Sorry I feel too friendly today... I've just suck some Lithium battery and oh god's that good for my mental health.

You talking about AJAX ? Yeah, that's a good blue thing.
![image](https://user-images.githubusercontent.com/21186871/81635957-916cb780-93e0-11ea-936b-09a9f27b6ca1.png)

**Comment by Undefined-Variables** [comment] 2020-05-12 03:42
BRILLIANT!!!

**Comment by polynamaude** [comment] 2020-05-12 04:05
@Undefined-Variables Shiny be a better word ;-)
If you want to host a forum for pH7CMS then I'll be happy to give you a hand. We could use Joomla as I already have licenses for some of the good extensions like JCE (Joomla Content Editor) Pro, two different template builder extension (drag & drop) don't get confused with drag and drip, that's a dead body story. I also have some own extensions already made, for example cloaking email adress from feeds, hiding software version and much more.

Also, Joomla is pretty light weight on resources when compared to some other CMS, it has it's own cache system (like pH7CMS) and much more. It even has a messaging system, comments on articles, rating, etc. I have the integration for Open Web Analytics too.

The only thing is that I'm not really an artist so we'll need to have someone do something for the design.

Here's my actual landing page [polynamaude](https://www.polynamaude.com/).

**Comment by Undefined-Variables** [comment] 2020-05-12 04:19
Yeah sounds good to me! CSS is what I do when I need to relax! Its the most enjoyable aspect of the process for me :) 

What should URL be? And where do I send you ftp/ssh login detals ?  Sending here openly is a really stupid idea haha! 

I had a good look at Joomla and created a half decent website in about 2hrs but I I kinda felt like my freedom was taken away! Its almost like a Lego set! All in packages ready to stitch together :) 

Developing for it is odiously more involve!

**Comment by polynamaude** [comment] 2020-05-12 04:34
@Undefined-Variables Well you missed most of the power of Joomla...
Go into the file **_templates/protostar/index.php_**
You will find tags like
```
<jdoc:include type="modules" name="position-8" style="xhtml" />
<jdoc:include type="modules" name="position-3" style="xhtml" />
<jdoc:include type="component" />
```
The first two say "replace this block by the module named **position-8** / **position-3**"
The last one say replace this block by the main component (more on that later).

Maybe you shall have looked at the developers documentation ;-)

https://docs.joomla.org/Portal:Developers

And that's a good intro on what are components
https://docs.joomla.org/Special:MyLanguage/J3.x:Developing_an_MVC_Component

And now for designing
https://docs.joomla.org/Web_designers

I think you get many thing confused...

A CMS is meant to be installed and designed mainly by developers but the day to day operation is meant for end-users. So for sure if you stayed in the menu, it felt like Lego but that would be like staying in the menu of pH7CMS but with way less stuff. So you want end-users to be able to change the places thing are and such but the real power come from the design of templates... And the best part override. For example, you can change only the css or the whole display of a module without re-writting it. You just write what's called a chrome and here you go. The module will do the processing and pass all the data to your chrome so it can make things the way it want.

And same goes for the templates.
And there's also plugin...

If I take your comment literally then pH7CMS is not a box of Lego but only a already made, glued together kit.

You probablu ended up using the Protostar template, that's basic Bootstrap simply...

Take another look...
Also the reason why it's so de-coupled is because you can access all the data (including articles) from the outside by using direct calls, like a headless CMS.

I'll send you my info tomorrow...
I got your email... from memory it's hey @ something . com

**Comment by polynamaude** [comment] 2020-05-12 04:38
@Undefined-Variables When you go into the configuration back-end you can select what modules are displayed, to what user level and with what menu options selected.

As for components, those are more complex piece of code and mainly do processing using the MVC pattern.

Stop making fast assumption, I could show you Joomla site that you don't even recognize...
Example...

https://etudier.uqam.ca/

**Comment by polynamaude** [comment] 2020-05-12 04:38
@Undefined-Variables btw, that's one of the biggest university in Canada... Over 100 000 students in 6 or 7 different city.

**Comment by Undefined-Variables** [comment] 2020-05-12 05:01
I think you are correct! The way I learned was opening notepad on windows and then watching a tutorial on YouTube like "php login system" I'd watch it a few times then have a go at doing it (without looking at the video again) and using php manual to try and understand! Nobody has ever sat down and explained anything to me and although I am able to do most things with php now its all self thought though trail and error! 

I'd love to have been able to do a full course on every little part but it just wasn't within my reach so I have done the best I could! 

I'm very comfortable with HTML, CSS, PHP, MySQL but there are parts I'm simply missing information on! 

Thing is though I do this because I enjoy it and was never planned as a carrier!

**Comment by polynamaude** [comment] 2020-05-12 05:36
@Undefined-Variables Yes you can learn all this in a structured manner but you have to force yourself into it. For example OpenClassroom Premium at 25USD/month and many more MOOC for example [fun mooc](https://www.fun-mooc.fr/)

Basicly now you are like a physician assistant that would see the diagnostic and the physician ordering her to pass some test to the patient. You're still missing the reasoning behind the scene.

And that's the hard part of doing so... Just learning boring, non practical stuff that seems useless but that you get to know later. When I look at the pH7CMS source code, pretty fast I see the pattern like Singleton, Observer, MVC, etc...

Take the time to learn those, there's books on Design Pattern laying around... books on Algorithms.... You'll save much time... That's pretty much like what we talked about investing some time to learn a IDE that will make you save much more on the long term.

I always been around computer and I've had to use them for programming when I did my master degree, but that wasn't related to computing and I could have done like most other people, just hire some geeks. And same when I did my PhD...

Yes, I did some computer classes but those we're optional class I could take during my years of University. In most Bacchelor and even some Master, you get one or two course, sometime more, that will be off-topic so I chose computer related subject for those.

And afterward I went to do some classes at adulte, part-time classes. I'm pretty sure you can find some in your local College that won't cost you much, England still has affordable (when compared to other) College level education, even more for part-time. Or even better, look out for a local Linux User Group... Well, now Meetups are a bit dead but they'll get back.

It's around 1:30 here so I'm heading to bed.

**Comment by Undefined-Variables** [comment] 2020-05-12 06:49
Yeah for a VERY long time I was missing the reasoning but honesty I have quite a good understanding of how Singleton and MVC work now, I picked up the basics working with bitwasp and talking to the author regularly helped a lot with that but I was still lost when I come accoss this but hard work, tones of reading and some great advice from yourself really helped get me this far even if I didn't want to hear it at the time! 

I went for an interview at the open university and had to sit a few papers to give them an idea of what I know and they adviced that I would need to do a Masters because I would find anything less boring as I have enough experience that basic HTML/CSS wouldn't be worth the 2yrs and cost of doing it! I agreed and they sent me the fees and cost in the post! 

A masters in web design would take 4yrs and cost £46,000 a year haha yeah okay! That's not small change and you are not earning while you study so its not feasible! 

Its 7.50am here I got to go pick up pain killers and hopeful postman might make my day then I'll be sleeping as well! 

I am going to look more in to this though that's for sure! My thought is if you don't try you will always wonder what if! I don't do regrets and what its I go for things and if it does happen at least I know I tried my best :)

**Comment by Undefined-Variables** [comment] 2020-05-12 19:10
Just need the okay from the big guy (pH7) and I will move forward with forum...

ph7cms-forum.com is available???

**Comment by polynamaude** [comment] 2020-05-12 19:27
@Undefined-Variables Hi,
I don't know if it's available, you can do an easy check but I don't think that's really needed. We can host over other domain.

If you want to give hand then I'll do the setup later this afternoon.

Now regarding training, don't get things wrong... There's nothing such as a MOOC Master degree, as Master degree is done after you did a Bacchelor degree and is partly research based, nothing compared to a MOOC (and mostly incompatible).
Yes there's school that say they offer such program but they worth not much more than a box of 500 pieces of papers. I'd call those school scam that just surf on people desire to get degree without going through the basis.

The first thing I learned in higher level education was that I don't know much and there's no easy explanation for anything on earth (or in space).

You can't just dive into a Master degree without going to at least a Bacchelor before, how will you able to understand the true meaning or research. It's not only about reading books and putting things forward. It's also about learning a way of thinking... To understand the global concept themselves...

If you want a hint, suffer a bit, go low on pills and you'll get more creativity, understand better the things around you. Not only a linear way (a step by step) but also as a whole...

Why would people do a Bacchelor and a Master afterward if you could just wait to be in your 30s and do so. Even more that most people doing such degree are often already adults...

The most important thing is credibility and when you say all those stuff, you loose a bit and doesn't help much. Stop looking for easy path or fast solution, the good one is the one that takes time and will make you proud of the work done.

**Comment by Undefined-Variables** [comment] 2020-05-12 22:51
@polynamaude Yes its available I checked earlier. I totally understand what you mean and this is what I  thought too and was only trying to explain how difficult people make this. 

I think the most important thing in life is honesty not credibility. If I said yes im a god at what I do knowing I am not just so people don't think badly of me id be cheating myself and not only lying to others but to myself too and that is not who I want to be.  I want to learn and learn in the right way. I am not worried about credibility that comes later once you have mastered your trade. 

I will grab this domain now and set it up, send me an email address to forward credentials too :)

**Comment by Undefined-Variables** [comment] 2020-05-12 22:53
Do you want me to upload/install Joomla or do you want to do it?

**Comment by polynamaude** [comment] 2020-05-13 01:35
@Undefined-Variables Credibility and honesty can go together. Buy being honest, you become credible.
Give me some time but you can install it yourself. My GF just got to the hospital so I'm not feeling too good.

**Comment by Undefined-Variables** [comment] 2020-05-13 02:06
@polynamaude oh shit sorry to hear that mate I hope she is okay! Yeah got to wait for domain to become active anyway! There is no big rush its just on the list :)

Hope everything is okay. If I can do anything you know where I am :)

**Comment by polynamaude** [comment] 2020-05-13 02:16
@Undefined-Variables To be honest, it's one of these day, one of these moment that I just fall on my knees. She's my little pearl, my diamond, the sunshine in the sky...

It also reminds me how cruel I can be with people and sometime rude...

**Comment by Undefined-Variables** [comment] 2020-05-13 02:24
That is such a lovely thing to hear. Don't mix up rude with honest! I admire your straight frowardness don't change that for anyone its awesome!

**Comment by polynamaude** [comment] 2020-05-13 02:49
![DSC_8167](https://user-images.githubusercontent.com/21186871/81765786-bd507180-94a2-11ea-940a-9ad6fe8c3339.JPG)

Photo of my little piece of wonderful.

Sometime when you are too honest people will dislike.

**Comment by polynamaude** [comment] 2020-05-13 02:51
@Undefined-Variables Sent a email.

**Comment by polynamaude** [comment] 2020-05-13 03:09
@Undefined-Variables Tell me if it's good...

**Comment by polynamaude** [comment] 2020-05-13 03:54
@Undefined-Variables You use Slack?

**Comment by Undefined-Variables** [comment] 2020-05-13 04:18
Where you send email? My real email is on my profile here :) Nothing in my inbox yet! Never heard of slack... Something useful?

**Comment by Undefined-Variables** [comment] 2020-05-13 04:25
Just joined slack looks interesting 

https://join.slack.com/t/undefined-variables/shared_invite/zt-eghmbmoh-DfzXqYXSqJIDc57EedRnjg

**Comment by polynamaude** [comment] 2020-05-13 04:33
@Undefined-Variables Sent you another email.. maybe I missed the dash in U-V vs UV

**Comment by pH-7** [comment] 2020-05-13 08:39
> @pH-7 Do you think running a forum specifically for the software would be beneficial to the software? Happy to host one if you think so. Its just this is about the 12th person who I've seen ask for it! Let me know

Hey @Undefined-Variables!

Sorry, I missed your question. Excellent idea. I actually plan this one for years, but never got the time to do so. 
There was even a  "forum" link in the "Help" menu of the admin panel, but it was never published
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/51760f369e30d057e91aa945be5b8e00e6c078e7#diff-5f87a902d133adbcad690c5b9220dfa7
If you create one, I will be glad to add your forum link in there.

Concerning the forum solution, my plan was to use Flarum https://flarum.org/ (it's a great one!), but at the end of the day, the software you are the most comfortable with will be the best fit. It doesn't worth spending too much time looking for the "right one"... 

Till August 2017, I was using the Sourceforge Forum, but it wasn't great and it was quite hard to maintain it.

**Comment by pH-7** [comment] 2020-05-13 08:44
> Just need the okay from the big guy (pH7) and I will move forward with forum...
> 
> ph7cms-forum.com is available???

Thanks for asking! I'm fine with either that domain name or another one.

**Comment by Undefined-Variables** [comment] 2020-05-13 10:51
In progress now I have your permission... I will email you your admin login details asap.

**Comment by Undefined-Variables** [comment] 2020-05-13 10:56
> > @pH-7 Do you think running a forum specifically for the software would be beneficial to the software? Happy to host one if you think so. Its just this is about the 12th person who I've seen ask for it! Let me know
> 
> Hey @Undefined-Variables!
> 
> Sorry, I missed your question. Excellent idea! 🎉 I actually plan this one for years, but never got the time to do so.
> There was even a "forum" link in the "Help" menu of the admin panel, but it was never published
> [51760f3#diff-5f87a902d133adbcad690c5b9220dfa7](https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/51760f369e30d057e91aa945be5b8e00e6c078e7#diff-5f87a902d133adbcad690c5b9220dfa7)
> If you create one, I will be glad to add your forum link in there.
> 
> Concerning the forum solution, my plan was to use Flarum https://flarum.org/ (it's a great one!), but at the end of the day, the software you are the most comfortable with will be the best fit. It doesn't worth spending too much time looking for the "right one"...
> 
> Till August 2017, I was using the Sourceforge Forum, but it wasn't great and it was quite hard to maintain it.

@pH-7 I have had a good talk with @polynamaude and she is keen to help and requested we use Joomla as she is at home using the cms and has many plugins/extensions that can be used. I didn't see any reason why not if she is able to create the important stuff I will then come behind and style it.  

Whent with ph7cms-forum.com btw

**Comment by Undefined-Variables** [comment] 2020-05-13 12:45
@pH-7 Sent you an email with previously spoken about details.

**Comment by pH-7** [comment] 2020-05-13 15:01
> @pH-7 Sent you an email with previously spoken about details.
Sweet! Really appreciate this. Do I need to do anything with it at the moment? Or just for later on, to maintain the forum...? Or maybe I missed something there?

> Went with ph7cms-forum.com btw
Woow, how amazing @Undefined-Variables! 🤩 You rock!! 💯

**Comment by Undefined-Variables** [comment] 2020-05-13 21:56
Hey @pH-7 no this is simply for access once running just keep it safe and upon first login you will be required to change password. I will let you know when its ready.

**Comment by pH-7** [comment] 2020-05-14 10:26
> this is simply for access once running just keep it safe and upon first login you will be required to change password. I will let you know when its

👍

**Comment by Undefined-Variables** [comment] 2020-05-14 19:15
> > > @pH-7 Do you think running a forum specifically for the software would be beneficial to the software? Happy to host one if you think so. Its just this is about the 12th person who I've seen ask for it! Let me know
> > 
> > 
> > Hey @Undefined-Variables!
> > Sorry, I missed your question. Excellent idea! 🎉 I actually plan this one for years, but never got the time to do so.
> > There was even a "forum" link in the "Help" menu of the admin panel, but it was never published
> > [51760f3#diff-5f87a902d133adbcad690c5b9220dfa7](https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/51760f369e30d057e91aa945be5b8e00e6c078e7#diff-5f87a902d133adbcad690c5b9220dfa7)
> > If you create one, I will be glad to add your forum link in there.
> > Concerning the forum solution, my plan was to use Flarum https://flarum.org/ (it's a great one!), but at the end of the day, the software you are the most comfortable with will be the best fit. It doesn't worth spending too much time looking for the "right one"...
> > Till August 2017, I was using the Sourceforge Forum, but it wasn't great and it was quite hard to maintain it.
> 
> @pH-7 I have had a good talk with @polynamaude and she is keen to help and requested we use Joomla as she is at home using the cms and has many plugins/extensions that can be used. I didn't see any reason why not if she is able to create the important stuff I will then come behind and style it.
> 
> Went with ph7cms-forum.com btw

We are developers we can't use someone else's work for our forum :) We are building our own from square one ;)

**Comment by polynamaude** [comment] 2020-05-14 19:40
@Undefined-Variables What's the problem with using other people software ? It's not because you're a developer that you can't use other people software or solution. It's not because I know how to cook a steak that I stopped going to McDonald's.

You need a good reason to go with a custom solution when there's something already existing by itself. By using a existing solution you get the advantages of support, bigger user base that will act as a test bed and it release you to do better stuff.

**Comment by Undefined-Variables** [comment] 2020-05-15 07:38
@polynamaude I take that back. You are correct I was wrong, my 3rd party software faith has been tested lately and I let that fuel my comment.
